### ISSUE TITLE
Cardinality dct:type on Licence Document

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/DCAT-AP#1]
Bert van Nuffelen, TenForce

Why is the the cardinality for dct:type on licenceDocument set to max 1? For some licenses more than one concept from  ADMS:LicenceType controlled vocabulary can apply.

**Comment by makxdekkers** [comment]
As far as remember, the cardinality of the licence type was not explicitly discussed in the Working Group during development. It was initially proposed as 0..1 and never challenged. There might have been the expectation that the ADMS licence types were mutually exclusive, but this is apparently not always the case. 

This change request can be put on the list for the next minor semantic release if the issue can be solved by increasing the maximum cardinality to 0..n. In addition, the issue can also be discussed in the context of the next major semantic release if there is a need to open a more fundamental discussion on licence types.

**Comment by makxdekkers** [comment]
Relevant approaches for future discussions include:

- Open Digital Rights Language ODRL: [https://www.w3.org/community/odrl/]
- Creative Commons Rights Expression Language (CC REL): [https://wiki.creativecommons.org]/wiki/CC_REL
- Open Data Rights Statement Vocabulary: [http://schema.theodi.org/odrs/]

**Comment by makxdekkers** [comment]
See also the in-depth discussion taking place at https://github.com/w3c/dxwg/issues/114.

**Comment by makxdekkers** [comment]
Proposed resolution | In next minor semantic release, change cardinality to 0..n. Retain issue for next major semantic release to discuss other ways of expressing characteristics of licences, for example as discussed in the Dataset Exchange Working Group at W3C. See: https://github.com/w3c/dxwg/issues/114

**Comment by bertvannuffelen** [comment]
Editorial comment on the DCAT-AP v1.1 published PDF: 

on page 26 dct:type is a mandatory property for LicenseDocument, but on p 15 it is stated a recommended property. So which one to follow?

**Comment by addragan** [comment]
dct:type is a recommended property for LicenseDocument based on the UML diagram. The documentation will be corrected at page 26 on next minor release in November 2018. Thank you for pointing it out.

**Comment by sandervd** [comment]
I see this change has been incorporated into release 1.2, can this issue be closed as fixed?

**Comment by addragan** [comment]
Issue fixed in release 1.2.
