### ISSUE TITLE
dcat:Dataset - remove adms:sample?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#10]
The DCAT-AP usage analysis on the European Data Portal showed the following:

adms:sample:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by DGatt** [comment]
Samples are of interest mostly if
 a) the data is not available as open data or
 b) only available as a bulk download, so large that it creates bandwidth/time issues

Both situations are not desirable in open data situations. On the other hand, German statistical data is often presented with the opportunity to download a completely empty table. This is similar but less formal to the case of a specification to which the datasets adheres to in its structure (this can be captured in Dataset - dct:conformsTo), and can be helpful in planning automated processing of the data (for example an XML or JSON schema could be referenced here). So I would argue to replace the property with one with a more relaxed use case/definition and range (rdfs:resource).

**Comment by makxdekkers** [comment]
I understand your would agree with removing the property from the profile, and add a new property. 
Three questions from my side:

1. what would the semantics of that new property be?
2. do you know any property in an existing namespace that has similar semantics?
3. is there already data that Germany could provide for such a property?

And of course, we would be interested to know if this is a requirement for other portals as well.

**Comment by makxdekkers** [comment]
@DGatt I am not entirely sure why the use case you outline, providing a link to a kind of template of the structure, could not be done with dct:conformsTo. After all, the DCMI definition of the range of the property [dct:Standard](http://dublincore.org/documents/dcmi-terms/#terms-Standard) is "_A basis for comparison; a reference point against which other things can be evaluated_". This seems sufficiently broad to also include such templates.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove adms:sample from Dataset.

**Comment by NatasaSofou** [comment]
Proposed Resolution: Keep adms:sample in Dataset.

**Comment by init-dcat-ap-de** [comment]
How about making it "deprecated"?
If the usage is still at 0% and the use case still unclear when the next major release is prepared, we can delete it safely.

**Comment by bertvannuffelen** [comment]
Since the semantics is still valid and meaningfull, and the comment is more driven from the perspective of having only properties in the specification document for which actual evidence is found in the practice, the notion of deprecation does not apply.  In that case we explicitely discourage the use of samples. Having the property does not harm. Therefore a won't fix.
