### ISSUE TITLE
Explicitly specify relations among Datasets, Distributions and DataServices

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#100]
Based on https://github.com/w3c/dxwg/issues/1126, it seems there is lots of freedom in interconnecting Datasets, Distributions and DataServices. This means it is not clear, how they should be interconnected. Lots of freedom means low interoperability.

I am suggesting adding a tighter specification to DCAT-AP 2.0.0 on how these should be connected in specific cases found today in Europe (SPARQL endpoints containing Datasets being a prominent case).
Also, the DCAT WG says that this specification is up to the communities adopting DCAT2.

Another solution would be leaving this issue to be implemented in possible national profiles of DCAT-AP 2.0.0, but this would IMHO hinder interoperability among EU portals, so I would be against it.

Currently, there is no guidance regarding this besides the syntactic description of the DataService class and related properties copied from DCAT2.

**Comment by bertvannuffelen** [comment]
resolution: to provide good guidelines more discussion and alignment is required

**Comment by bertvannuffelen** [comment]
During WG 15 sept 2021 and WG 21 Oct 2021, the wg was presented an approach to address the questions related to this issue. The result is an updated UML diagram and an usage guideline for Datasets, Distributions and Data Services.
