### ISSUE TITLE
typo in URI "dcat:centroid"

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#102]
page 19 shows:
centroid | dcat:centoid | rdfs:Literal | This property refers to the geographic center   (centroid) of a resource.

should be:
centroid | dcat:cent**r**oid | rdfs:Literal | This property refers to the geographic center   (centroid) of a resource.

![image](https://user-images.githubusercontent.com/14979304/67489849-82a3fa80-f672-11e9-8dbf-76f82ee6ef0a.png)

**Comment by bertvannuffelen** [comment]
resolved

**Comment by bertvannuffelen** [comment]
resolved
