### ISSUE TITLE
typo in change log: dct:status mentioned which does not exist

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#103]
in the change log it is mentioned that in DCAT-AP version 1.2.1 the vocabulary for dct:status was changed (in addition to updates to adms:status in 2.0.0). 
This looks like an error, as dct:status does not seem to exist.

![image](https://user-images.githubusercontent.com/14979304/67490833-28a43480-f674-11e9-9860-f43605c26173.png)

**Comment by bertvannuffelen** [comment]
resolved
