### ISSUE TITLE
DCAT version

### ISSUE THREAD

**Issue by idevisser** [SEMICeu/DCAT-AP#104]
The DCAT Application Profile defined in this document is based on the Data Catalog Vocabulary (DCAT) - Version 2, W3C Working Draft 28 May 2019.

Please support the the final version of (DCAT) - Version 2 when it becoms available. An in between version is not preferable.

Noted differnces in the UML;
The abstract class dcat: Resource is missing in DCAT-AP. By this, relations regarding the dcat:DataService class are missing in this profile.
Also the dct:license  in dcat:Dataset is missing, this part of the most recent version of DCAT.
dcat:Distribution has a relation dcat:accessService with dcat:Dataset, this seems not correct.

**Comment by bertvannuffelen** [comment]
The reference to the version will be w.r.t. to the most recent public draft version. In a future bugfix release, updates to the reference will be done. We assume that the current DCAT 2.0 will not change too much compared to the public draft.

UML differerences:
In another issue is has been decided that dcat:Resource will not be explicitly included, but that the properties which are relevant for DCAT-AP (i.e. those on which DCAT-AP wants to express additional constraints or put emphasis on) are added to the base entities (Dataset, DataService, Catalogue).

On dct:license see the comment in the specific issue #108 .

On dcat:accessService: addressed in UML figure
