### ISSUE TITLE
Fine tuning of dcat:Relationship

### ISSUE THREAD

**Issue by hoverbee** [SEMICeu/DCAT-AP#105]
Chapter 7. AGENT ROLES
The current proposal introduces dcat:Relationship in order to extend the possible resource-Agent relations beyond dct:publisher and dct:creator.
However, this could lead to multiple ways to express the same semantics, which could complicate interoperability. As is recognized, but not mitigated by the last section of this chapter. Do we need to keep the dct:publisher and dct:creator properties?

In the class diagram (figure 1) dcat:Relationship relates to Dataset, Catalog, (and not to dcat:DataService). In the text in 3.3 that talks about "DCAT Resources" (but not dcat:Resources). that throws questions about the extend to which dcat is followed.

See also issues #100 and #104.

**Comment by bertvannuffelen** [comment]
@hoverbee if I am right dcat:Relationship is a general relationship between dcat:Resources, hence datasets, data services and catalogs.

The additional relations between dcat:Resource and foaf:Agent are only the two dct:publisher and dcat:creator.

**Comment by bertvannuffelen** [comment]
resolution: feedback provided
