### ISSUE TITLE
Type in class distribution

### ISSUE THREAD

**Issue by idevisser** [SEMICeu/DCAT-AP#107]
In the case a service has not specific separate service metadata, it is needed to have in the distribution class more information about the type off the accessURL, like is it a view or download or OGC:WFS or OGC:WMS etc.
In DCAT it looks like a type property is added in the distribution to support this;

  dct:type <https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view>

**Comment by bertvannuffelen** [comment]
@idevisser this the intention of a dcat:DataService. I think we should take the alignment to DCAT 2.0 as an opportunity to reconsider our thinking on datasets and distributions, taking into account the existence of data services. 
The idea that a distribution is a REST, SPARQL or WFS service is more DCAT 1.0. (There was no alternative, and it was never satisfactory.)  In DCAT 2.0 the preferred usage would consider them as data services offering access to one or more datasets. 
In that line of thought, distributions become more static snapshots as a file dump.

**Comment by bertvannuffelen** [comment]
resolution: feedback provided

**Comment by bertvannuffelen** [comment]
resolution: more discussions on data services are foreseen
