### ISSUE TITLE
Data service class

### ISSUE THREAD

**Issue by idevisser** [SEMICeu/DCAT-AP#109]
The Dataservice class is modelled to provide more information about an endpointURL. 
If it is intended that this should be support the ISO 19119 metadata, i see a problem.
The ISO 19119 metadata provided for INSPIRE descibes an accesspoint ( OGC:WMS, OGC:WFS etc). This accesspoint contains different operations and endpoints. So a part of the ISO 19119 should be mapped to the distribution class and an other part to the dataservice class. 
There is discussion in the INSPIRE community if this  ISO 19119 service metadata is still nessacerry, it is a dublicate of the capabilities and  dataset metadata. 
If it is intended to support the existing INSPIRE service metadata, then changes are needed. In other cases it seems to be able to work. 

At least more explanation is needed to implement this dataservice class comparable all over Europe.

**Comment by bertvannuffelen** [comment]
Guidelines on data services require more discussion.

**Comment by bertvannuffelen** [comment]
During WG 15 sept 2021 and WG 21 Oct 2021, the wg was presented an approach to address the questions related to this issue. The result is an updated UML diagram and an usage guideline for Datasets, Distributions and Data Services.
