### ISSUE TITLE
add cardinality constraint max 1 on dcat:temporalResolution 

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#114]
From the comment on https://github.com/SEMICeu/DCAT-AP/issues/78#issuecomment-554794438, and https://github.com/SEMICeu/DCAT-AP/issues/76#issuecomment-554794160

> 
> Just like on the dataset level:
> I think both dcat:temporalResolution and dcat:spatialResolutionInMeters should have a maximum  cardinality of 1, currently it says "0..n" in the specification.

**Comment by bertvannuffelen** [comment]
To the community:

2 topics here: 
  a) Do we restrict the spatialResolution & temporalResolution for a dataset? 
  b) Do we restrict the spatialResolution & temporalResolution for a distribution?

If no support for either of the proposals is given, then the proposal is not to apply the restrictions.

**Comment by bertvannuffelen** [comment]
wg of 21 oct 2021 decided to apply the max cardinality in order to remove the incoherency between the usagenote text which refers to the minimum value.
And to apply this in all cases.

**Comment by andrea-perego** [comment]
@bertvannuffelen :

> wg of 21 oct 2021 decided to apply the max cardinality in order to remove the incoherency between the usagenote text which refers to the minimum value. And to apply this in all cases.

Although this would make sense for distributions, setting the max cardinality to 1 for datasets will be in contrast with the practice of publishing multiple distributions of the same dataset, each with different resolution - e.g., the NUTS.

**Comment by bertvannuffelen** [comment]
In the WG the attention was drawn to the word "minimum". So in the example, the minimum (most precise) resolution of all NUTS distributions should be used as value for the resolution.
