### ISSUE TITLE
shacl/v.1.2.1 - dcat:contactPoint doesn't accept a vcard:Organization

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#115]
We tested a few of our datasets with the EDP tool (https://www.europeandataportal.eu/shacl/) and found that some validation errors are falsely:

Example RDF: https://www.govdata.de/ckan/dataset/strassenverkehrsunfalle-in-schleswig-holstein-im-november-2007-vorlaufige-zahlen.rdf

**XML:**
```
    <dcat:contactPoint>
      <vcard:Organization rdf:nodeID="Na2e4f48af3e841e4815c265ba26e1d3d">
        <vcard:fn>Statistisches Amt für Hamburg und Schleswig-Holstein</vcard:fn>
        <vcard:hasEmail rdf:resource="mailto:info@statistik-nord.de"/>
      </vcard:Organization>
    </dcat:contactPoint>
```

**Error:**
```
    {
      "@id": "_:b9",
      "@type": "sh:ValidationResult",
      "focusNode": "http://opendata.schleswig-holstein.de/dataset/StaNord_CMS:55265",
      "resultMessage": "Value does not have class http://www.w3.org/2006/vcard/ns#Kind",
      "resultPath": "dcat:contactPoint",
      "resultSeverity": "sh:Violation",
      "sourceConstraintComponent": "sh:ClassConstraintComponent",
      "sourceShape": "_:b13",
      "value": "_:b12"
    }
```

**Possible reason/problem in the SHACL-files:**
vcard:Organization is a subclass of vcard:Kind and therefor should not throw this error.

**Background**
dcat-ap.de is a German variation of dcat-ap. Our goal was, that all valid dcat-ap.de files are also valid dcat-ap files. We only reduced options and added specific fields.

GovData.de is (for example) a data portal where dcat-ap.de is used. GovData.de data is also collected by the EDP. We are now trying to improve the meta data quality, especially the dcat-ap compliance (https://www.europeandataportal.eu/mqa/govdata?locale=en).

Also posted at: https://gitlab.com/european-data-portal/mqa/shacl-validation/issues/1

**Comment by bertvannuffelen** [comment]
see #116

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, it has been decided not to upgrade the historic SHACL representations and focus on the new representations.

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, it has been decided not to upgrade the historic SHACL representations and focus on the new representations.
