### ISSUE TITLE
dcat:Dataset - remove dct:accessRights?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#12]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:accessRights:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by oystein-asnes** [comment]
Norway might be a cornercase, but we are using this property to be able to combine open data with other data in the same catalouge/UI/dataportal. This is not exposed to/through EDP, hence the 0% usage. A beta of the portal can be seen here: https://fellesdatakatalog.brreg.no/?lang=en.  It looks like this in the JSON-LD API: 

dct:accessRights: {
@id: "http://publications.europa.eu/resource/authority/access-right/PUBLIC"
},
If the property is to be removed from DCAT-AP, we will still keep it in DCAT-AP-NO, and only expose "PUBLIC" datasets to EDP

**Comment by makxdekkers** [comment]
Given the comment from @oystein-asnes, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by addragan** [comment]
Issue rejected due to disagreement comments. The issue will be closed with no changes in the specification.
