### ISSUE TITLE
shacl/v.1.2.1 - How to use "dct:spatial"?

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#120]
I could not find a working example on how to use dct:spatial in the context of EDP and DCAT-AP 1.2.1 that validates against the existing shacl-shapes.

Can you provide an example or best practice? 

https://joinup.ec.europa.eu/release/how-should-dctspatial-and-dctlocation-be-used was for 1.1.

Also posted at: https://gitlab.com/european-data-portal/mqa/shacl-validation/issues/6

**Comment by bertvannuffelen** [comment]
This requires more elaboration. Surely since the DCAT-AP 2.0 put more stress on the specific properties dcat:centroid and dcat:bbox.

**Comment by init-dcat-ap-de** [comment]
The W3C draft provides many examples for the use of `dcterms:spatial`, e.g.: https://w3c.github.io/dxwg/dcat/#ex-spatial-coverage-geometry

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, the wg decided not to address this issue. The wg participants agreed that for the moment the examples in W3C DCAT are sufficient.
