### ISSUE TITLE
shacl - Examples and Best Practices Needed

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#121]
dcat-ap.de is a German variation of dcat-ap. Our goal was, that all valid dcat-ap.de files are also valid dcat-ap files. We only reduced options and added specific fields.

GovData.de is (for example) a data portal where dcat-ap.de is used. GovData.de data is also collected by the EDP. We are now trying to improve the meta data quality, especially the dcat-ap compliance (https://www.europeandataportal.eu/mqa/govdata?locale=en).

Often we are not sure if we provide the information in a wrong form or if the SHACL-files have errors. We would love to get examples and best practices for all features of DCAT-AP 1.2 and 2.0 to align DCAT-AP.de and improve interoperability.

Also posted at: https://gitlab.com/european-data-portal/mqa/shacl-validation/issues/7

**Comment by bertvannuffelen** [comment]
This discrepancy has been mentioned to the EDP team. They are working towards an improved quality assessment measurement.

**Comment by bertvannuffelen** [comment]
A more elaborated SHACL validator https://www.itb.ec.europa.eu/shacl/dcat-ap/upload has been provided.
The configuration can be found at https://github.com/ISAITB/validator-resources-dcat-ap. 
An explanation on SHACL & validation can be found at https://github.com/SEMICeu/DCAT-AP/blob/2.1.0-draft/releases/2.1.0/examples/examples.md
