### ISSUE TITLE
The Catalog Class - UsageNote update?

### ISSUE THREAD

**Issue by aidig** [SEMICeu/DCAT-AP#128]
The usage note of the class dcat:Catalog is currently:

> A catalogue or repository that hosts the Datasets being described.

One of the main changes in DCAT 2.0 is the addition of a dcat:Resource class for representing any asset than can be included in the catalog as well as the addition of dcat:DataService to support catalog service end-points providing access to data assets. The fact that dcat:Dataset and dcat:DataService are both resources that can be catalogued is poorly reflected in the above usage note. 

Also, note that definition of catalogue in DCAT 2.0: 
> A curated collection of metadata about resources (e.g., datasets and data services in the context of a data catalog).

Might the usage note in this EU Data Portal context possibly benefit from better alignment with the DCAT definition, if indeed such portal could catalogue both dataset and dataservices.

**Comment by aidig** [comment]
This comment applies to the class Catalog Record too.

**Comment by andrea-perego** [comment]
@aidig said:

> This comment applies to the class Catalog Record too.

Actually, it applies also to other class descriptions and properties.

E.g.:
- Agent:
  > An entity that is associated with Catalogues and/or Datasets.
- Category:
  > A subject of a Dataset.
- Document:
  > A textual resource intended for human consumption that contains information, e.g. a web page about a Dataset.
- Frequency:
  > A rate at which something recurs, e.g. the publication of a Dataset.
- Standard:
  > A standard or other specification to which a Dataset or Distribution conforms

**Comment by bertvannuffelen** [comment]
proposal:

to align the definitions and usagenotes when a new textual (HTML) representation is being build.

motivation:

Although the definitions and usagenotes are not perfectly aligned with those in W3C DCAT, they are not incorrect either. When building a new master specification (HTML) the distinction between definition/usage note and the reference to W3C DCAT can be included. Because this work is a major editorial effort.

**Comment by bertvannuffelen** [comment]
Connected with #150

**Comment by init-dcat-ap-de** [comment]
If I understand the proposal correctly, the upcoming (already findable) web version will have updated descriptions for many properties and classes.

Will you provide an overview/comparison? 
It will take time (and maybe many github issues) to find & discuss changes.
