### ISSUE TITLE
dcat:Dataset - remove dct:hasVersion?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#13]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:hasVersion:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.
The Dataset Exchange Working Group at W3C also considers the requirements for versioning, see the [issues](https://github.com/w3c/dxwg/issues?q=is%3Aissue+is%3Aopen+version+label%3Aversion) at the [DXWG GitHub repository](https://github.com/w3c/dxwg). A future version of DCAT-AP should take into account resolutions from the discussion at DXWG.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by addragan** [comment]
The issue will be closed with no changes in the specification.
