### ISSUE TITLE
Incorrect Time ontology IRIs in JSON-LD context and RDF

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#131]
Both in the [JSON-LD context](https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.0.0/dcat-ap_2.0.0.jsonld#L135) and the [RDF version](https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.0.0/dcat-ap_2.0.0.rdf#L1383) of DCAT-AP 2.0.0 the IRIs of properties from the Time ontology are incorrectly prefixed with `https://www.w3.org/TR/owl-time/#time:` (used to link to HTML sections in the document) instead of `http://www.w3.org/2006/time#`. This is a major interoperability issue.

**Comment by bertvannuffelen** [comment]
add also missing time: prefix in the master specification (word document).
