### ISSUE TITLE
References to Category and Category scheme outdated

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#135]
In the PDF-version of DCAT-AP v.2.0.0, 3.2. Recommended Classes: References to Category and Category scheme point to an outdated version of DCAT.

**Comment by akuckartz** [comment]
> DCAT 2 supersedes DCAT [VOCAB-DCAT-20140116], but it does not make it obsolete. ... Any new implementation is expected to adopt DCAT 2, while the existing implementations do not need to upgrade to it, unless they want to use the new features. In particular, current DCAT deployments that do not overlap with the DCAT 2 new features (e.g., data services, time and space properties qualified relations, packaging) don't need to change anything to remain in conformance with DCAT 2.
https://www.w3.org/TR/vocab-dcat-2/

**Comment by bertvannuffelen** [comment]
see #128

**Comment by bertvannuffelen** [comment]
connected with #135
