### ISSUE TITLE
Proposal for adding property "identifier" (dct:identifier) to Class "Agent" (foaf:Agent)

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#141]
dct:identifier (range rdfs:Literal)
preferably as "recommended" (0..1)

**Comment by andrea-perego** [comment]
In case it could turn to be useful, identifiers for agents are supported in the DCAT-AP profile used in the JRC Data Catalogue (https://data.jrc.ec.europa.eu/) for multidisciplinary research data. BTW, the JRC profile of DCAT-AP uses for this purpose both `dct:identifier` and `adms:identifier`.

A discussion on the underlying requirements:

https://ec-jrc.github.io/dcat-ap-jrc/#req-identifiers

Identifiers for agents (organisations and individuals):
- `dct:identifier`:
  - https://ec-jrc.github.io/dcat-ap-jrc/#agent-organisation-identifier
  - https://ec-jrc.github.io/dcat-ap-jrc/#agent-individual-identifier
- `adms:identifier`:
  - https://ec-jrc.github.io/dcat-ap-jrc/#agent-organisation-other-identifier
  - https://ec-jrc.github.io/dcat-ap-jrc/#agent-individual-other-identifier

There are also a couple of examples showing how they are used:

https://ec-jrc.github.io/dcat-ap-jrc/#ex-agent-organisation

https://ec-jrc.github.io/dcat-ap-jrc/#ex-agent-individual

**Comment by jimjyang** [comment]
Sorry for my late response, @bertvannuffelen, and sorry that I didn't provide any rationale when I wrote this proposal. 

Yes, the reference provided by @andrea-perego very well covers my request. Thanks, @andrea-perego!

**Comment by bertvannuffelen** [comment]
decision from wg of 21 oct 2021: postpone the resolution of this issue to have a broader discussion on identifiers.

**Comment by bertvannuffelen** [comment]
We propose to close this issue as in release 3.0.0 in section on [Identifiers ](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#identifiers) a reference is made to the outcome of a community discussion on identifiers.

In case new use-cases or expectations or harmonisation proposals are needed we propose to open a new issue and start the discussion from that section.
