### ISSUE TITLE
Proposal for adding property "conforms to" (dct:conformsTo) to Class "Data Service" (dcat:DataService) 

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#142]
dct:conformsTo (range dct:Standard)
as "optional" (0..*) 

The "Usage note" for "endpoint description" also mentions explicitly dct:conformsTo: "The property [endpoint description] gives specific details of the actual endpoint instances, while dct:conformsTo is used to indicate the general standard or specification that the endpoints implement."

**Comment by jakubklimek** [comment]
I.e. so that we can query for "all SPARQL endpoints", "all WMS services", etc., right? @jimjyang

**Comment by bertvannuffelen** [comment]
During WG 15 sept 2021 and WG 21 Oct 2021, the wg was presented an approach to address the questions related to this issue. The result is an updated UML diagram and an usage guideline for Datasets, Distributions and Data Services. 

Additional explanation to the expectation on optional fields and fields not mentioned but present in DCAT has been added.
