### ISSUE TITLE
dcat:endpointURL vs. dcat:endPointIRL 

### ISSUE THREAD

**Issue by fabiankirstein** [SEMICeu/DCAT-AP#143]
The DCAT-AP 2.0 specification defines the endpoint URL of a DataService as dcat:endPointIRL, where DCAT itself names it dcat:endpointURL (https://www.w3.org/TR/vocab-dcat-2/#Property:data_service_endpoint_url). Is this on purpose? And if so, what is the reason for that renaming? Thanks!

**Comment by jakubklimek** [comment]
@fabiankirstein can you provide a link to where you see this? Seems to me like a clear mistake, I checked the .rdf and .pdf versions of DCAT-AP v2.0.0 and they both say `dcat:endpointURL` as they should.

**Comment by fabiankirstein** [comment]
@jakubklimek You are right! I had the PDF version issued on 04.10.2019 on my local machine. But there is already an updated version, from 20.11.2019. So my mistake, I though if the version number is the same, it is the same document. 

![grafik](https://user-images.githubusercontent.com/1488424/84869371-3a609f00-b07e-11ea-818f-3bae62e93710.png)
