### ISSUE TITLE
Using VocBench 3 for managing DCAT-AP?

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#148]
Since it is an "European" application, has there been thoughts on unsing [VocBench 3](https://ec.europa.eu/isa2/solutions/vocbench3_en) for managing DCAT-AP?

The question is not fully altruistic, since your questions would help us to evaluate whether or not VocBench could be useful for managing DCAT-AP.de.

**Comment by EmidioStani** [comment]
I noticed that such request is similar to https://github.com/SEMICeu/SDG-sandbox/issues/49
