### ISSUE TITLE
Modelling three-level structures with DCAT/ADMS

### ISSUE THREAD

**Issue by aidig** [SEMICeu/DCAT-AP#149]
In the current application of DCAT-AP/ADMS-AP for the JoinUp catalogue of interoperability solutions, the following structure is applied:

1. **solution level** (e.g. [Core Public Service Vocabulary](https://joinup.ec.europa.eu/solution/core-public-service-vocabulary)) -> **dcat:Dataset**
2. **release level** (e.g. [Core Public Service Vocabulary v. 1.01](https://joinup.ec.europa.eu/release/core-public-service-vocabulary/101))  -> **dcat:Dataset**
3. **distribution level** (e.g. [Core Public Service Vocabulary v. 1.0 TTL](https://joinup.ec.europa.eu/solution/core-public-service-vocabulary/distribution/cpsv-ttl))  -> **dcat:Distribution**

Here, both the solution and the versioned releases are described using [dcat:Dataset](https://www.w3.org/TR/vocab-dcat-2/#Class:Dataset) and the releases are related to the solution using dct:isVersionOf.

Other options have previously been discussed (eg. [ADMS CR 21 Asset](https://joinup.ec.europa.eu/solution/asset-description-metadata-schema-adms-revision/discussion/cr21-asset-remove-admslast-admsnext-admsprev-properties-and-replace-them-property-dctisversionof)) , but can the above method now be considered the advised method to model three-level structures in the DCAT-AP community?

**References:**
https://github.com/SEMICeu/ADMS-AP/issues/30
https://joinup.ec.europa.eu/solution/asset-description-metadata-schema-adms-revision/discussion/cr21-asset-remove-admslast-admsnext-admsprev-properties-and-replace-them-property-dctisversionof

**Comment by bertvannuffelen** [comment]
The use and way of working for ADMS has been disentangled from DCAT in release of ADMS 2.0.0 (https://semiceu.github.io/ADMS/releases/2.00/)

**Comment by bertvannuffelen** [comment]
With the publication of ADMS as SEMIC recommendation (https://semiceu.github.io/ADMS/releases/2.00/) we close this issue.
