### ISSUE TITLE
Release DCAT-AP as a web page (HTML document)

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#150]
Could we release DCAT-AP as a web page instead of (or in addition to, but I do not see a reason for that) a Word, ODT and a PDF document?

Frankly, releasing a web specification in a non-web format is rather embarrassing.

I recommend [Bikeshed](https://github.com/tabatkins/bikeshed) or [respec](https://github.com/w3c/respec), as those two are uses for the majority of web specifications.

Use cases:
- I would be able to link to a part of a specification from another specification
- I would be able to read the spec comfortably on any device without additional software
- The style would be consistent with other specifications, increasing readability and trustworthiness

**Comment by EmidioStani** [comment]
As observation: the Flemish Government is already publishing each vocabulary as web page using the starting point the data model (UML), see e.g: https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog/

It needs to be decided the starting point (the UML ? the ontology ? the word document ?).

As there is already the persistent uri service data.europa.eu it could be nice to use such portal to expose all the vocabularies in all the formats (as it already exist for eu budget or ADMS controlled vocabularies) and not only perform a redirection to joinup

**Comment by jakubklimek** [comment]
Yes, in Czechia we also publish each vocabulary (and related schemas and examples) as a respec web page. See https://ofn.gov.cz (in Czech, but you can click on any of the items in the lists, or just Google Translate), or specifically, the [Czech DCAT-AP 2.0.1 implementation](https://ofn.gov.cz/rozhraní-katalogů-otevřených-dat/draft/)

**Comment by jakubklimek** [comment]
Btw. GeoDCAT-AP is now also developed in ReSpec, see https://github.com/SEMICeu/GeoDCAT-AP/issues/14#issuecomment-668766966

**Comment by EmidioStani** [comment]
And in Denmark the SHACL shapes are the starting point:

https://github.com/SEMICeu/DCAT-AP/issues/126#issuecomment-621042058

**Comment by bertvannuffelen** [comment]
This request is part of the current activity to improve the management and accessibility of the Core Vocabularies.
A easy to explore web presence with correct dereferencing is part of it.
