### ISSUE TITLE
Duplicate content: Submission guidelines as PDF and in Wiki

### ISSUE THREAD

**Issue by k00ni** [SEMICeu/DCAT-AP#152]
Submission guidelines information is located both in PDF (https://github.com/SEMICeu/DCAT-AP/blob/master/DCAT-AP_Issue_submission_guidelines_v0.01.pdf) and in the wiki (https://github.com/SEMICeu/DCAT-AP/wiki/Submission-guidelines).

**Are you open to only use one document containing this information?**

Using PDF files could make it harder for people using accessibility technology to access information (e.g. https://accessibility.psu.edu/pdf/pdfissues/). Another reason against it is that Github users can't contribute to the PDF file because its considered a binary.

Using the wiki might also not be the right place. The wiki is only accessible via Github, but it seems this repository is also used in other places.

Therefore I would argue that a simple Markdown/Textfile should be enough. When its Markdown the file is rendered via Github and could almost look as nice as the current PDF. Also it allows contributions by others.

What do you think?

**Comment by bertvannuffelen** [comment]
@k00ni thank you for the comment. We will take that in the current activity to improve the presence and management of the Core Vocabularies.

**Comment by bertvannuffelen** [comment]
SEMIC is continuously improving its process and followup of the issues, governance and the publication of the specifications.
In the past years, the community has found its way to GitHub for reporting comments and participating in discussions.
With the publication of the specifications in HTML as main human readable format, this path will continued, working towards an open easy accessible place.
