### ISSUE TITLE
dcat:Dataset - remove dct:source?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#16]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:source:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:source from dcat:Dataset.

**Comment by NatasaSofou** [comment]
It is proposed to keep this property in the model for now.
