### ISSUE TITLE
SHACL - The ranges of the properties dcat:hadRole and dct:relation on dcat:Relationship

### ISSUE THREAD

**Issue by aidig** [SEMICeu/DCAT-AP#160]
In the DCAT-AP SHACL implementation of the class dcat:Relationship, the range of the property dcat:hadRole is the DcatResource_Shape (dcat:Catalog, dcat:Dataset or dcat:DataService) wheras the range of dct:relation is dcat:Role.

Shouldn't it be the other way around in the context of dcat:Relationsship?

Also, the UML diagram only visualises the the application of dct:relation (on dcat:Relationship) with dcat:Dataset as the range (not dcat:Catalog or dcat:DataService)

**Comment by aidig** [comment]
...and whilst on the subject of dct:relation on dcat:Relationship... 

should     
`sh:nodeKind <https://data.gov.dk/model/profile/dcat-ap-dk/DcatResource_Shape> ; `
possibly be changed to:
`sh:node <https://data.gov.dk/model/profile/dcat-ap-dk/DcatResource_Shape> ;`

**Comment by bertvannuffelen** [comment]
well spotted. The range of dcat:hadRole is dcat:Role. I'll propose an update in the next draft.

**Comment by bertvannuffelen** [comment]
About the diagram. When the release 2.0.0 was build, the diagram was minorly updated to keep it condensed. But as you points out, in some cases this does not yields the intended representation. In the upcomming geoDCAT-AP release a variant of the diagram is proposed which tries to get this balance better.
