### ISSUE TITLE
SHACL-Webinar: Error Messages / sh:severity

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#164]
Thank you again for doing the SHACL-Webinar and releasing the [screencast](https://www.youtube.com/watch?v=9I8IOhsg2hg). We now had a chance to revisit the discussed problems and solutions. (See: #162)
We want to move forward with the validation of DCAT-AP.de for GovData.de and we would like to do so by re-using the shapes from DCAT-AP.

Around the one hour mark, we discussed the mapping of the usage level in DCAT-AP to the severity-level of SHACL. I think we all agreed, that the mapping 
```
“mandatory   --> violation”, 
“recommended --> warning” and 
“optional    --> no rule/info” 
```
was correct.

Unfortunately the [shacl-specification](https://www.w3.org/TR/shacl/#conforms) says that “the value of sh:conforms is true **if and only if** the validation did **not** produce **any validation** results”. 

We think that this should not influence the construction of the SHACL-rules. Instead, the EDP should not rely on `sh:conforms`, but instead check whether or not “true violations” have occurred.

Otherwise we would have to split the rules in different files so that the EDP could use the “violations only” rules for compliance testing.

**Comment by bertvannuffelen** [comment]
As mentioned in the request, the issue cannot be resolved by adapting or reorganizing the SHACL shapes. It is mainly an interpretation issue at the level of the implementation at the EDP.

On behalve of the DCAT-AP specification, in the draft,  the SHACL specification is splitted in several files. The implementation of the recommended property constraints will yield an additional SHACL file.

**Comment by bertvannuffelen** [comment]
A shacl file containing the recommended properties is added in the proposal: https://github.com/SEMICeu/DCAT-AP/blob/2.1.0-draft/releases/2.1.0/dcat-ap_2.1.0_shacl_shapes_recommended.ttl
