### ISSUE TITLE
announcement > public review of GeoDCAT-AP 2.0.0

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#167]
Dear community,

GeoDCAT-AP 2.0.0, the extension of DCAT-AP for spatial datasets,  is out for public review. This release mainly aligns GeoDCAT-AP with DCAT-AP 2.0.1 and DCAT 2.0, but also addresses a number of smaller issues.

The candidate proposal can be found at https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/. Your feedback is welcome on the github at https://github.com/SEMICeu/GeoDCAT-AP/issues.

You are also invited to join the webinar on the 9th of November about this release. More information about the webinar can be found at https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/news/geodcat-ap-20-webinar.

kr,

The SEMIC team

**Comment by jakubklimek** [comment]
@bertvannuffelen On the joinup page I did not find a link to join the webinar. Will a recording be available?

**Comment by bertvannuffelen** [comment]
@jakubklimek the recording has been made. I will followup on the publication of it.
