### ISSUE TITLE
dcat-ap_2.0.1.rdf not in sync with PDF specification

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#168]
While testing the include-file for shacl rules (#163) I checked the rdf-version of DCAT-AP 2.0.1. 
There you state
`<rdfs:subClassOf rdf:resource="http://www.w3.org/ns/dcat#Dataset"/>`

If this is true, there is no representation of this fact in the PDF specification or in the UML diagram.

**Comment by bertvannuffelen** [comment]
DCAT-AP is a profile from DCAT. So all constraints and relationships expressed by DCAT apply.  

In particular, for the case that a catalog is a subclass of dataset is problematic, we have to address this at W3C.  In our DCAT-AP setting we consider catalogs and datasets as something distinctive yet having similar properties.   

The UML graph, unfortunately, has become a mix between things that are explicit and implicit. Besides the discussion what should be on or not on the figure, we also can consider the readibility  if it.

**Comment by bertvannuffelen** [comment]
Catalogue being a subclass of Dataset results in some "profiling" interpretation issues. Registered as issue in https://github.com/w3c/dxwg/issues/1387 on W3C.

**Comment by bertvannuffelen** [comment]
Improved the UML figure should address some of the readibility issues.
