### ISSUE TITLE
Consider switching to https://schema.org

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/DCAT-AP#169]
Schema.org moved to https, so there is a redirection from http to https and all the classes and examples are in https.

Switching to https would use a secure protocol and avoid (the small) waiting time for redirection mechanism.

**Comment by jakubklimek** [comment]
However, this would also break all existing implementations, as the IRIs will become different on RDF model level.
This would have to be solved by additional application logic specific to schema.org in every DCAT-AP implementation.

Therefore, this is a major breaking change.

**Comment by EmidioStani** [comment]
I agree on the impact, until http redirection exist it is fine to keep http then.
