### ISSUE TITLE
dcat:Dataset - remove dct:type?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#17]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:type:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by DGatt** [comment]
DCAT-AP.de tries to use dct:type to model time series and other types of collections:
A dataset of the type "collection" (http://www.dcat-ap.de/def/datasetTypes/) has no distributions but via dct:hasVersion references other datasets that are (e.g. yearly) slices of the data. This way all members of the time series are grouped together as versions of the same Collection (denoted in dct:isVersionOf). This is a better approach than the widespread modelling of time series as - informationally  different! - distributions of one dataset. The same approach could be taken to group structurally equivalent but informationally different sets of data for different regions. In the end it would even make it possible to curate the metadata by grouping similar datasets from different data contributors/data portals.

**Comment by makxdekkers** [comment]
The German solution to grouping time slices or related geographical data is a possible resolution of this issue that the DCAT-AP working group discussed in the past. 
However, it is different from the Guideline https://joinup.ec.europa.eu/release/dcat-ap-how-model-dataset-series which recommends to use a dataset type of 'series' and to link to the individual years using dct:hasPart.
Further comments on this solution from other implementers are most welcome.

**Comment by giorgialodi** [comment]
Can we use the profile in order to provide metadata for "documents" (seen as a collection of unstructured data)? In many open data catalogues there are lots of PDF files! If so, this property may be used to distinguish between the different types: datasets, dataset series, geospatial datasets, documents, etc. But we need to identify (or create?) a controlled vocabulary. Probably the absence, in the current specifications, of the related controlled vocabulary limits its usage. 
My2cents!

**Comment by makxdekkers** [comment]
There is a [discussion](https://github.com/w3c/dxwg/issues/64) in the Dataset Exchange Working Group around a requirement to "Provide a mechanism to indicate the type of data being described and recommend vocabularies to use given the dataset type indicated". A future version of DCAT-AP should take into account a resolution of the issue by DXWG.

**Comment by makxdekkers** [comment]
See discussion at https://github.com/w3c/dxwg/issues/64.

**Comment by DGatt** [comment]
@makxdekkers As far as I can see, the Guidelines and the German solution differ only in the properties used to express the relation beteween series and individual sclice. The properties dct:hasPart and dct:isPartOf which are recommended in the Guideline however only seem to be defined for the catalog, not the dataset.
@giorgialodi I fully endorse the idea of creating a controlled vocabulary. In fact, as mentioned above we do have such a list in Germany (http://www.dcat-ap.de/def/datasetTypes/1_0.html#collection), albeit with only one entry ("collection"). I'm not very enthusiastic about mixing metadata for structured an unstructured information, though, as in my eyes thy both require very different user-interfaces for browsing and searching. But of course, one can always set appropirat filters.

**Comment by makxdekkers** [comment]
@DGatt You are right that the approach suggested in the guideline requires the inclusion of `dct:isPartOf` and `dct:hasPart` for Dataset in the profile. This can be discussed in the context of the next major release -- also taking into account the outcome of the discussions at DXWG.
@DGatt @giorgialodi There is a controlled vocabulary on the European level at http://publications.europa.eu/mdr/authority/dataset-type/, but that does not, at the moment, include types related to dataset series and collections.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by andrea-perego** [comment]
Just to note that the use of `dct:type` for denoting the specific type of resource is supported in GeoDCAT-AP. The relevant code list (covering datasets, dataset series and services) is the one operated by the INSPIRE Registry (and it is based on ISO 19115):

http://inspire.ec.europa.eu/metadata-codelist/ResourceType

The relationship between series and child resources (datasets or other series) is specified by using `dct:hasPart`. This reflects the approach used in ISO 19115, where a series can be used to hierarchically organise datasets (where datasets are leaves, whereas series are nodes of the tree).

**Comment by NatasaSofou** [comment]
It is proposed to keep this property in the model for now. Note discussion at DXWG, see: https://github.com/w3c/dxwg/issues/64
