### ISSUE TITLE
Max cardinality for dct:creator

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/DCAT-AP#171]
Currently, the max cardinality of `dct:creator` is set to 1 instead of N. 

This implies that a dataset or a catalogue can have at most 1 author/creator, which is not the case.

**Comment by bertvannuffelen** [comment]
This is an question to the community. 

In general I agree there is the possibility that there are multiple author/creators for a catalogue or dataset.

But the definition (section 4.4.3)

_This property refers to the entity primarily responsible for producing the dataset_ 

already addresses the question by the word _primarily_ into the definition.

This limitation has been set based on the DCAT-AP objective to aid Open Data Portals to communicate a dedicated minimal amount of information that is helpful for the possible reuser to make an reuse decision. So although there might be multiple creators/authors of the dataset, for the objective of an Open Data Portal is one sufficient. 

NOTE: This issue raises also opens the discussion on the max-cardinality requirements on other roles. Should they be revised too?

**Comment by andrea-perego** [comment]
Thanks, @bertvannuffelen , for explaining the rationale behind the cardinality constraint on `dct:creator`.

About this point:

> This limitation has been set based on the DCAT-AP objective to aid Open Data Portals to communicate a dedicated minimal amount of information that is helpful for the possible reuser to make an reuse decision. So although there might be multiple creators/authors of the dataset, for the objective of an Open Data Portal is one sufficient.

Such assumption depends very much on the actual purpose of having `dct:creator` in DCAT-AP. E.g., it may be not only related to reuse, but also to acknowledge the parties who contributed to the creation of a resource - which involves provenance, accountability, and IPR aspects.

Actually, one of the reasons why `dct:creator` was included in DCAT2 was to address one of the requirements of research data - namely, data citation (see the note in [§6.4.4](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_creator))

For this specific use case, restricting the max cardinality of `dct:creator` to 1 creates a barrier for the use of DCAT-AP for documenting research data - while a number of initiatives, as the European Open Science Cloud (EOSC) are working toward this objective, and not to mention that (public-funded) research data fall in the scope of the Open Data Directive.

Besides this, there's another more practical aspect to take into account, i.e., how `dct:creator` has been (and is being) used in existing DCAT-AP extensions, and whether any max cardinality constraint has been specified.

Looking at the national extensions documented in [the 2017 report on Joinup](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/document/national-extensions-analysis-dcat-ap), those using it at the time the report was written (DCAT-AP.de, DCAT-AP_IT, DCAT-AP-NO) have no max cardinality constraint. 

Other examples are GeoDCAT-AP, which supports this property since its first release, and - talking about research data - the DCAT-AP extension ([CiteDCAT-AP](https://ec-jrc.github.io/datacite-to-dcat-ap/)) used by [Zenodo](https://zenodo.org/) (the most widely used research data repository in Europe, currently including ~2M metadata records).

This situation suggests that allowing the specification of multiple authors meets cross-border and cross-domain requirements.

**Comment by jakubklimek** [comment]
> Looking at the national extensions documented in the 2017 report on Joinup, those using it at the time the report was written (DCAT-AP.de, DCAT-AP_IT, DCAT-AP-NO) have no max cardinality constraint.

Technically speaking, this just means they are all incorrect, as they violate the cardinality constraint of DCAT-AP, which a profile should not do.

But from the interoperability perspective, I see this as an unnecessary restriction and unless there is a clear EU-specific reason to limit this to one, I would remove the restriction, and I would remove them from the other roles as well.

**Comment by ODP-hil** [comment]
Although in favour of changing max cardinality for `dct:creator` of `dcat:Dataset`, this should be assessed also in consideration of the range defined by DCAT-AP 2.0.1 as `foaf:Agent`.
For a `foaf:Agent` creator the 0...1 cardinality makes sense and should be kept. If, however, range is relaxed to allow also `foaf:Person` then the 0...n cardinality would make more sense and would support data citation.
For reference, on [data.europa](https://data.europa.eu/en).eu some 7000+ datasets have a `foaf:Person` creator harvested from [these ](https://data.europa.eu/sparql?default-graph-uri=&query=PREFIX+dcat%3A+%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0D%0APREFIX+dct%3A+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0D%0A%0D%0Aselect+distinct+%3Fcat%0D%0Awhere+%7B%0D%0A%3Fcat+a+dcat%3ACatalog%3B%0D%0Adcat%3Adataset+%3Fds.%0D%0A%3Fds+a+dcat%3ADataset%3B%0D%0Adct%3Acreator+%3Fcreator.%0D%0A%3Fcreator+a+%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FPerson%3E%0D%0A%7D%0D%0A&format=text%2Fhtml&timeout=0&signal_void=on)catalogues.

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, the wg agreed to the proposal to lift the cardinality.
