### ISSUE TITLE
Range of temporal properties

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/DCAT-AP#172]
The range of properties as `dct:issued` and `dct:modified` is described as follows:

> `rdfs:Literal` typed as `xsd:date` or `xsd:dateTime`

There are however cases when only the year is used.

The above description could be revised as follows:

> `rdfs:Literal` typed as `xsd:date`, `xsd:dateTime`, or `xsd:gYear`

**Comment by akuckartz** [comment]
Maybe this brief discussion helps: https://github.com/OpenGovLD/specs/issues/109

**Comment by andrea-perego** [comment]
> Maybe this brief discussion helps: [OpenGovLD/specs#109](https://github.com/OpenGovLD/specs/issues/109)

Thanks, @akuckartz .

In addition to this, DCAT 2 allows any time-related datatypes. More precisely, the range of these properties is defined as follows:

> `rdfs:Literal` encoded using the relevant ISO 8601 Date and Time compliant string [DATETIME] and typed using the appropriate XML Schema datatype [XMLSCHEMA11-2] (`xsd:gYear`, `xsd:gYearMonth`, `xsd:date`, or `xsd:dateTime`).

See, e.g., [§6.4.7 Property: release date](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_release_date).

**Comment by bertvannuffelen** [comment]
This issue asks for a relaxation of the range requirement. Are there users that need support for more coarse grained temporal information?

**Comment by jakubklimek** [comment]
I do not need support for this, as in Czechia these are always dates or dateTimes. However, I think we should stay in sync with DCAT unless there is a serious reason to diverge.

Personally, I would like to see a solution based on [W3C Time Ontology](https://www.w3.org/TR/owl-time/) but that is a completely different approach.

**Comment by bertvannuffelen** [comment]
On W3C time ontology, that is worth exploring, but out of scope for this request.

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, the wg decided to align with W3C DCAT to allow all temporal xsd types.
