### ISSUE TITLE
dcat:Distribution - inconsistent specification of what the range is for dct:format?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#173]
dct:format points to dct:mediaType in the UML-diagram, while the the PDF-version and the shacl-version has dct:MediaTypeOrExtent as the range for dct:format.

**Comment by andrea-perego** [comment]
Only to note that this inconsistency results in a validation error (`sh:Violation`) for GeoDCAT-AP 2 records, where `dct:MediaType` is used.
