### ISSUE TITLE
Vocabulary URI "dcatap:availability" is linking to "Joinup" 

### ISSUE THREAD

**Issue by GKStGovData** [SEMICeu/DCAT-AP#178]
According the PDF document, the Distribution availability vocabular should be available under http://data.europa.eu/r5r/availability/  following this URI i get forwarded to the DCAT-AP JoinUp Website: https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe 
What's the correct URI?

**Comment by GKStGovData** [comment]
@ODP-hil thx for the reply. Are there plans for maintaining a list? At www.dcat-ap.de/def  we are hosting our "dcatde-specific-lists" for example: https://www.dcat-ap.de/def/plannedAvailability/

**Comment by init-dcat-ap-de** [comment]
I would like to add that the only ways to get the *mandatory* values are
1) find the rdf, which is not directly available from the dcatap-namespace or
2) guess the IRIs by combining the base from page 23 (Vocabulary URI) with the values stated in the change log.

Not very user friendly, at the moment.

**Comment by ODP-hil** [comment]
EU Publications Office will maintain this as a controlled vocabulary. Please refer to [Adding dcatap:availability to dcat:Resource #190](https://github.com/SEMICeu/DCAT-AP/issues/190#issuecomment-825494317 ) to review proposed solutions.

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, the wg was informed about the publication of a new NAL under the goverance of the Publications Office.
