### ISSUE TITLE
References for Classes

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#179]
Hello,

the specification gives as reference e.g. for dcat:Catalog: http://www.w3.org/TR/2013/WD-vocab-dcat-20130312/#class-catalog
but the rdf-version says `<rdfs:isDefinedBy rdf:resource="https://www.w3.org/TR/vocab-dcat-2/#Class:Catalog"/>`.

I would guess it was simply not updated.

**Comment by bertvannuffelen** [comment]
See #128, #135

**Comment by init-dcat-ap-de** [comment]
All links provided unter *Reference in DCAT* point (e.g.) to https://w3c.github.io/dxwg/dcat/#Class:Dataset

Shouldn't they point to a stable version, like https://www.w3.org/TR/vocab-dcat-3/#Class:Dataset

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de, the URL will be updated.

**Comment by bertvannuffelen** [comment]
Change applied in (draft specification)[https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/].
