### ISSUE TITLE
dcat:Dataset - remove owl:versionInfo?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#18]
The DCAT-AP usage analysis on the European Data Portal showed the following:

owl:versionInfo:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by NatasaSofou** [comment]
It is proposed to keep the property in the model for now.
