### ISSUE TITLE
Make dcat:dataset recommended (0..*) for dcat:Catalog

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#180]
Hello,

with the introduction of dcat:DataService and dcat:catalog, which result in catalogs of dataservices or catalogs of catalogs, it isn't reasonable to have dcat:dataset as mandatory.

I think it was never, why should it be forbidden to post information about an empty catalog, but now I think the change is necessary.

**Comment by bertvannuffelen** [comment]
This is good point. It is hard(er) to enforce now an empty catalog. 
2 options:

- remove the mandatory constraint (relaxing the DCAT-AP specification), or
- express the constraint in a different way.

Checking if the catalog is empty is probably something that implementations will impose as a quality check. So maybe it is not required to add this to the specification, as this might be more a decision by the implementations

**Comment by init-dcat-ap-de** [comment]
We would vote for option 1. 
If someone sees value in publishing an empty catalog, I don't see why it should be forbidden.

**Comment by bertvannuffelen** [comment]
During WG 15 sept 2021 and WG 21 Oct 2021, the wg was presented an approach to address the questions related to this issue. The result is an updated UML diagram and an usage guideline for Datasets, Distributions and Data Services. 

Additional explanation to the expectation on optional fields and fields not mentioned but present in DCAT has been added.
