### ISSUE TITLE
dct:relation in the dcat:Relationship Class mandatory or optional?

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#181]
Hello,

there is a mismatch wether dct:relation is mandatory or optional:
![grafik](https://user-images.githubusercontent.com/14979304/107936647-2cec1380-6f83-11eb-96bb-6f3e8c3d4478.png)

My guess is, it's mandatory, because that's the way it is stated in the textual part of the specification.

**Comment by akuckartz** [comment]
That graphic also contains this requirement: "dct:relation: [1..n]"
