### ISSUE TITLE
dct:MediaTypeOrExtent still in specification

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#185]
The specification still lists dct:MediaTypeOrExtent as range of dct:format.
It should be dct:MediaType. In the UML diagram it is correct.

![grafik](https://user-images.githubusercontent.com/14979304/107962341-2079b200-6fa7-11eb-89dc-1433ba1a0eea.png)

**Comment by jimjyang** [comment]
See also #173.

**Comment by bfrichet3** [comment]
Dear @bertvannuffelen 

I hope you are all right. I am not sure I perfectly understood the way you fixed the problem. I do read in [the technical specifications of DCAT AP 2.1](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/distribution/dcat-ap-210-pdf) that dct:format's range is still dct:MediaTypeOrExtent (see p.18).

Does that mean dct:MediaTypeOrExtent is still the appropriate range of that proprerty or does that mean that there is still a mistake (or myabe it means I didn't catch anything to that discussion.

Regards,

Benoît
