### ISSUE TITLE
dcat:Dataset - harmonise the use of dct:accrualPeriodicity

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#19]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:accrualPeriodicity:
•	Usage: 44.98%
•	Issue: some datasets are using the URIs of the MDR Frequencies NAL while other datasets use the label of the same authority list.
•	Is there a need for guidelines to harmonise usage across implementations?

**Comment by makxdekkers** [comment]
According to the specification of DCAT-AP, conforming implementations MUST use the URIs of the MDR Frequencies NAL.

**Comment by makxdekkers** [comment]
Proposed resolution | No change to the specification.

**Comment by addragan** [comment]
The issue will be closed and no changes will be done to the specification.
