### ISSUE TITLE
dct:coverage for Distributions

### ISSUE THREAD

**Issue by sabinem** [SEMICeu/DCAT-AP#197]
In DCAT-AP-CH we have a property dct:coverage on dcat:Distribtution. I kind of struggle with this property:
-  is does not seem very Swiss specific and there are dct:spatial and dct:temporal that would be able to cover all the use cases, that we have, for datasets
- on distributions however, there is only dcat:spatialResolutionInMeters and dcat:temporalResolution which is a duration not a point in time.

Our most important use case:
We have Datasets that cover all election in Switzerland from a certain year to another year and where each distribution covers the election results of just one year. For these datasets we use the coverage property on distribution and the property value is the election date.

What is your opinion on that custom dct:coverage property in our application profile. It has the range dct:LocationPeriodOrJurisdiction and the domain dcat:Distribution and dcat:Dataset. 
Does this conform DCAT-AP. Or can we replace it an any way with a property of DCAT-AP.

Help with this issue would be very much appreciated

**Comment by jakubklimek** [comment]
> each distribution covers the election results of just one year

This is, however, an anti-pattern (see the [note in Distribution](https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution)), as the distributions should differ only in format, not in content. For this use case, you should use the [dataset relation constructs](https://www.w3.org/TR/vocab-dcat-2/#qualified-relationship). E.g. in Czechia, we use `dcterms:hasPart` and `dcterms:isPartOf` to build a dataset hierarchy, where the top dataset has no distributions, and the contained datasets are the "per year" datasets, parts of the top dataset. This is per the [usage note of Relationship](https://www.w3.org/TR/vocab-dcat-2/#Class:Relationship), which then supports more complex relations.

**Comment by init-dcat-ap-de** [comment]
@jakubklimek is right, but before implementing series of Datasets in another Swiss-special way, take a look at the state of DCAT3: https://www.w3.org/TR/vocab-dcat-3/#Class:Dataset_Series
