### ISSUE TITLE
dcat:Distribution - usage of dct:title and dct:format

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#20]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:title and dct:format:
•	Usage: 77.17% and 12.17% respectively
•	Issue: Some distributions use dct:title instead of dct:format to provide information about the format of the distribution.
•	Is there a need for guidelines to explain how to use dct:title and dct:format?

**Comment by makxdekkers** [comment]
There is no reason to discourage distribution titles like "CSV distribution of <some dataset>" as this provides useful human-readable information to users. However, the provision of machine-readable information  in dct:format is already encouraged as this is a recommended property for Distribution.

**Comment by DGatt** [comment]
In fact, as very often nothing but the format differntiates to distribution, the alternative to titles lide "CSV distribution of..." would be to have identical titles for the distribution. Not ideal.

**Comment by makxdekkers** [comment]
@DGatt I agree.

**Comment by makxdekkers** [comment]
Proposed resolution | No change to the specification.

**Comment by addragan** [comment]
The issue will be closed and no changes will be done to the specification.
