### ISSUE TITLE
add optional property dct:type to dcat:Distribution

### ISSUE THREAD

**Issue by ODP-hil** [SEMICeu/DCAT-AP#202]
The open data catalogue of the European Union uses `dct:type` to classify `dcat:Distribution` with values from EU Controlled Vocabulary [Distribution Type](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/distribution-type).
Available terms include:
- [DOWNLOADABLE_FILE](http://publications.europa.eu/resource/authority/distribution-type/DOWNLOADABLE_FILE)
- [FEED_INFO](https://publications.europa.eu/resource/authority/distribution-type/FEED_INFO)
- [VISUALIZATION](https://publications.europa.eu/resource/authority/distribution-type/VISUALIZATION)
- [WEB_SERVICE](https://publications.europa.eu/resource/authority/distribution-type/WEB_SERVICE)

This property can be useful in distinguishing between Distributions available as file download, through a data service or visualisations of datasets.

Would you you consider recommending this as an optional property for DCAT-AP?

**Comment by bertvannuffelen** [comment]
@ODP-hil , I would consider this in the context of DCAT-AP 1.2.x solely. In the context of DCAT-AP 2.x there are data services, a notion introduced for that purpose. 

In https://github.com/SEMICeu/DCAT-AP/issues/144 you find some explorations on this. But in short for me, except for the first one, all are data services. 

- Feeds are services that provide information about the changes in the data
- Visualisations, except a static image,  are services that allow to explore the data in a complex way. (e.g. dashboards, geoportals, ...)
- web services are obviously data services. 

As a general comment, many of our DCAT-AP discussion topics have to do with this kind of questions. Maybe it is good that the community can make a list of cases that mostly are excepted to be data services and others that are distributions. And create so a living guideline on this categorization.

**Comment by ODP-hil** [comment]
@bertvannuffelen - Indeed all but the first one are actually data services but `dct:type` could be useful in defining data service as distribution and the relationship between the two classes (case B.1 in [issue #144](https://github.com/SEMICeu/DCAT-AP/issues/144#issuecomment-786032117)).

Drawing from [example 12 of DCAT 2.0](https://www.w3.org/TR/vocab-dcat-2/#ex-access-service), adding 'dct:type' VISUALIZATION will further clarify that the distribution is a visualisation available via a data service: 
```
:dataset-004
  rdf:type dcat:Dataset ;
    dcat:distribution :dataset-004-png ;
  .

:dataset-004-png
  rdf:type dcat:Distribution ;
  dcat:accessService :figure-service-006 ;
  dcat:accessURL <http://example.org/api/figure-006> ;
  dcat:mediaType <https://www.iana.org/assignments/media-types/image/png> ;
  dct:type <https://publications.europa.eu/resource/authority/distribution-type/VISUALIZATION> ;
  .

:figure-service-006
  rdf:type dcat:DataService ;
  dct:conformsTo <http://example.org/apidef/figure/v1.0> ;
  dct:type <https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view> ;
  dcat:endpointDescription <http://example.org/api/figure-006/params> ;
  dcat:endpointURL <http://example.org/api/figure-006> ;
  dcat:servesDataset :dataset-004 ;
  .
```
A list of cases drawn by the community will also be useful in eventually enriching the [Distribution Type](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/distribution-type) Authority Table and possibly advocate the creation of a Data Service Type Authority Table (e.g. API, SPARQL endpoint, download service).

**Comment by bertvannuffelen** [comment]
During WG 15 sept 2021 and WG 21 Oct 2021, the wg was presented an approach to address the questions related to this issue. The result is an updated UML diagram and an usage guideline for Datasets, Distributions and Data Services. 

The usage and alignment of this codelist has not discussed in depth with the community. Therefore it put as future work.
