### ISSUE TITLE
Range of `dcat:spatialResolutionInMeters` and `dcat:temporalResolution`

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#206]
For dates (`dct:issued`, etc.) the range is: `rdfs:Literal typed as xsd:date or xsd:dateTime`
For `spdx:checksumValue` the range is: `rdfs:Literal typed as xsd:hexBinary`
For `dcat:byteSize` the range is: `rdfs:Literal typed as xsd:decimal`

Only for `dcat:spatialResolutionInMeters` and `dcat:temporalResolution` the range is given as `xsd:decimal` and `xsd:duration` directly.

We think, it should be done in the way of `rdfs:Literal typed as xsd:..........`.

Or is there a reason, other than "dcat is doing it this way"?

**Comment by makxdekkers** [comment]
I will notify W3C about this inconsistency in DCAT.

**Comment by makxdekkers** [comment]
Se https://github.com/w3c/dxwg/issues/1420

**Comment by makxdekkers** [comment]
Solved at W3C. See [pull request 1421](https://github.com/w3c/dxwg/pull/1421)
