### ISSUE TITLE
Availability description error in the https://raw.githubusercontent.com/SEMICeu/DCAT-AP/2.1.0-draft/releases/2.1.0/dcat-ap_2.1.0.rdf file

### ISSUE THREAD

**Issue by keestrautwein** [SEMICeu/DCAT-AP#208]
Hi,

Looking at https://raw.githubusercontent.com/SEMICeu/DCAT-AP/2.1.0-draft/releases/2.1.0/dcat-ap_2.1.0.rdf we noticed that at the end of the file there is an error in the description of "http://data.europa.eu/r5r/availability/experimental"

I think that the definition of "experimental" should be different from "available".  I think the skos:definition of "experimental" should be something like:
<skos:definition xml:lang="en">Data might be available for a short period, short term planning.</skos:definition>

**Comment by bertvannuffelen** [comment]
Suggestion:

Data is available on a trial basis for a short period, short term planning.

**Comment by bertvannuffelen** [comment]
Publications Office has been informed also about the new definition.
