### ISSUE TITLE
dcat:Distribution - remove dct:rights?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#21]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:rights:
•	Usage: near 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by DGatt** [comment]
I think the property would benefit from some clear guidance as to what content is expected int the referenced document (all covered by the definition of the class ):

- a statement about the intellectual property rights (IPR) held in or over a Resource,
- a legal document giving official permission to do something with a resource (seems to be already covered by dct:license) ,
- a statement about access rights (which would bring this property into the focus of issue #34 ).

**Comment by makxdekkers** [comment]
Please note that there is a discussion on this issue also in the Dataset Exchange Working Group (DXWG) at W3C in the context of the revision of DCAT; see https://github.com/w3c/dxwg/issues/114.
The definition at DCMI may be read to imply that anything that is a statement about rights of whatever kind can be the object of `dct:rights`.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:rights from Distribution.

**Comment by NatasaSofou** [comment]
It is proposed to keep it in the model for now. Note discussion at DXWG, see: w3c/dxwg#114.
