### ISSUE TITLE
Why does DCAT-AP has a frequency vocabulary of its own?

### ISSUE THREAD

**Issue by sabinem** [SEMICeu/DCAT-AP#210]
I am having a question from users of the Swiss DCAT-AP CH that I cannot answer myself: it is about the frequency vocabulary:

Why did DCAT-AP come up with its own frequency vocabulary https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/frequency mandatory instead of using the DCAT vocabulary: https://www.dublincore.org/specifications/dublin-core/collection-description/frequency/

(see https://github.com/opendata-swiss/dcat_ap_ch/issues/52#issuecomment-973836394) 

Can anyone share background information on this topic?

**Comment by bertvannuffelen** [comment]
@sabinem I do not recall all possible reasons (even if the dcterms was already existing prior the creation of the NAL, or that both already existed a long time parallel to the list in dcterms). 

But usually the reasons to create a controlled vocabulary under your own governance is motivated because you have values that the other doesn't have, and that it is hard to influence the other controlled vocabulary to adopt the new values.

Comparing both, you see that the NAL has many more values. It is an indication of this.

A second argument, which especially holds for the the EU is that those NALs can be requested to be provided in all EU memberstate languages. This is also beneficial.

**Comment by sabinem** [comment]
@bertvannuffelen Thank you very much. I already suspected that is was about the additional values. But the language argument is convincing too. And I totally understand that is helps to have control over the vocabulary and be able to adjust it to the communities needs.

**Comment by l00mi** [comment]
Thank you also from my side, the multilingual labels are indeed an additional value.
After having a closer look it seems that the EU List is actually pointing with `skos:exactMatch` to the DCterm list where it applies, have look e.g. in [BIWEEKLY](https://op.europa.eu/en/web/eu-vocabularies/concept/-/resource?uri=http://publications.europa.eu/resource/authority/frequency/BIWEEKLY) for "Has Exact Match". Which would suggest that the EU list was based on the DCterm list.

**Comment by tibaiti** [comment]
Some historical background from [OP Controlled vocabularies](https://op.europa.eu/en/web/eu-vocabularies): 
The [frequency](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/frequency) authority table was created for the request of the OP Cataloguing Team which manages metadata of the general publications. It was first published on 2015-06-10. This first publication contained 21 out of its 30 concepts nowadays, including the 17 dcterms which were linked with sameAs property. The NAL was already multilingual at birth, containing labels in 24 EU official languages; it also had mappings with 19 internally used PUB_FREQ values of the Cataloguing Team.
The 2016-02-17 publication added the concept ‘never’ for the request of the [EU ODP](https://data.europa.eu/en).   
The 2016-03-16 publication completed the original multilingualism with Norwegian labels.
The 2019-02-20 publication added four other concepts and the 2019-06-19 publication four another ones.
So this NAL was not specifically created for ODP and/or DCAT-AP purposes but can be useful and skos:exactMatch ensures the relation with the DCAT vocabulary.
