### ISSUE TITLE
Link to the extended changelog? 

### ISSUE THREAD

**Issue by GKStGovData** [SEMICeu/DCAT-AP#212]
Thanks for publishing the draft version https://github.com/SEMICeu/DCAT-AP/tree/2.1.0-draft/releases/2.1.0 
On the last Page it says "The extended changelog can be found in github." 

Unfortunately I could not find a changelog, which would be really helpful to check the draft version. 
Could you please paste the link here? 

Thx!

**Comment by bertvannuffelen** [comment]
@GKStGovData  this one I am now compiling.

But this is the list that impacted the specification:
- https://github.com/SEMICeu/DCAT-AP/labels/release%3A2.1.0-dec2021

The issues with won't fix will be also closed.

kr,

Bert

**Comment by GKStGovData** [comment]
Hi @bertvannuffelen thx for you quick response, perfect timing :) Since we don't have much time to go through the detailed TIckets again, we are looking forward to the change log.

**Comment by bertvannuffelen** [comment]
@GKStGovData the changelog has been created: https://github.com/SEMICeu/DCAT-AP/blob/2.1.0-draft/releases/2.1.0/CHANGELOG.md

**Comment by GKStGovData** [comment]
@bertvannuffelen thank you for providing the changelog, it really helped us to analyze the changes and the impact on DCAT-AP.de. Thank you also for asking. For the current release we have no further points to the tickets brought so far.
