### ISSUE TITLE
DCAT-AP 2.1.0 distributions missing in Joinup

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#215]
The [DCAT-AP 2.1.0 page on Joinup](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/release/210) is missing the actual distributions.
Also, the [GitHub releases](https://github.com/SEMICeu/DCAT-AP/releases) are missing 2.1.0.

**Comment by bertvannuffelen** [comment]
@jakubklimek the github release has been created and is available. For JoinUp, the distributions will be created, but the plan is that github is the place to find the formal details of the specification, as for JoinUp these are downloaded copies.
