### ISSUE TITLE
SHACL: Property Shapes Without a Test?

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#219]
Do we need Property Shapes which don't test anything? Or am I missing something?

```
[
  sh:path dct:language ;
  sh:severity sh:Violation
]
```

https://github.com/SEMICeu/DCAT-AP/blob/55617123a940d00f781cc9204b572f9ab46776e1/releases/2.1.0/dcat-ap_2.1.0_shacl_shapes.ttl#L149

**Comment by bertvannuffelen** [comment]
There are here two perspectives. 

a) If the SHACL is solely for validation then this constraint will never fire, and is useless statement.

b) If one wants to generate a form from the SHACL or to use it as a specification then it is useful. Namely an entry for that property can be generated Or it is included in the list of (endorsed) properties in the specification.

In the creation of the SHACL I just added a reference to each property. Resulting more a style suited for b) although only case a) is the real objective.

**Comment by init-dcat-ap-de** [comment]
Okay, thank you.
