### ISSUE TITLE
Change the way DCAT-AP is written up in RDF

### ISSUE THREAD

**Issue by sabinem** [SEMICeu/DCAT-AP#220]
I am currently learning about RDF and RDFS and I was really surprised about some facts that I learned from https://workingontologist.org/.

One such fact I learned about RDF was that there is interference, but not really a concept for inheritance. This means properties are classes are just as classes are classes themselves in RDFS. Properties have a Range and a Domain, which are again Classes that denote which classes the Objects and Subjects of the property triples may belong to. But as far as I understood Properties are not owned by Classes in any way (see https://www.w3.org/TR/rdf-schema)

I like that this concept of interference instead of inheritance is still visible in the way DCAT is written up in Turtle, see here: https://github.com/w3c/dxwg/blob/3f953341888ae01b4dce74ecedb12c1febf894f0/dcat/rdf/dcat3.ttl. Even though DCAT is broad, it's RDF version is very compact and easy to read.

I would appreciate to have a similar version of DCAT-AP. That would also helps its users to understand more of the semantic foundations on which the DCAT-AP is build. The RDF version of DCAT-AP 2.1.0 https://github.com/SEMICeu/DCAT-AP/blob/55617123a940d00f781cc9204b572f9ab46776e1/releases/2.1.0/dcat-ap_2.1.0.rdf on the other hand might easily be read as if properties are owned by classes, when this is not really the case. 

Would it be possible to go more in the directions of DCAT with this RDF version of DCAT-AP in the future, or is there any obstacle  using this approach on profiles of DCAT?

**Comment by bertvannuffelen** [comment]
@sabinem  this representation will be part of the change when we create a new html representation.

**Comment by bertvannuffelen** [comment]
This topic is also related to the how profiles work and how this reflects in an RDF representation.

**Comment by bertvannuffelen** [comment]
In the SEMIC [Style Guide ](https://semiceu.github.io/style-guide/1.0.0/index.html) general guidelines for the  application profile's artifacts are being described.

In this case we separate the RDF representation for the application profile from the RDF representation of the namespace for additional DCAT-AP terms. This additional vocabulary is found here: https://semiceu.github.io/DCAT-AP/r5r/releases/3.0.0/.  For this a RDF representation has a clear usage and expectation pattern.  For the application profile the focus is on the HTML  and the SHACL representation.
