### ISSUE TITLE
http://data.europa.eu/r5r/ links to e-Government Core Vocabularies on joinup

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#221]
Hello,
dcatap`s namespace http://data.europa.eu/r5r/ redirects to https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/e-government-core-vocabularies, a page for the e-Government Core Vocabularies.

In my opinion, a redirect to https://github.com/SEMICeu/DCAT-AP would be more helpful.
Or https://raw.githubusercontent.com/SEMICeu/DCAT-AP/master/releases/2.1.0/dcat-ap_2.1.0.rdf
Or https://raw.githubusercontent.com/SEMICeu/DCAT-AP/2.1.0-draft/releases/2.1.0/dcat-ap_2.1.0.rdf
Or maybe https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de the redirection was indeed wrong (copy of the wrong target). We pointed it now to https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe.

**Comment by andrea-perego** [comment]
@bertvannuffelen , there's the same problem with the GeoDCAT-AP namespace URI: 

http://data.europa.eu/930/

Ideally, it should point to where all the versions (HTML, RDF, and SHACL) are available:

https://semiceu.github.io/GeoDCAT-AP/releases/

**Comment by bertvannuffelen** [comment]
@andrea-perego I will look to it (although the problem is slightly different than the one above ) ;-)

**Comment by ODP-hil** [comment]
http://data.europa.eu/r5r/ redirection was updated to https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe.
An exception was made for http://data.europa.eu/r5r/availibility which previously redirected to https://raw.githubusercontent.com/SEMICeu/DCAT-AP/2.1.0-draft/releases/2.1.0/dcat-ap_2.1.0.rdf but now redirects to the terms included in the [planned-availability controlled vocabulary](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/planned-availability) (see: https://github.com/SEMICeu/DCAT-AP/issues/178 and https://github.com/SEMICeu/DCAT-AP/issues/190).

Redirections from http://data.europa.eu/930/* to http://uri.semic.eu/geodcatap/* are in progress.

**Comment by andrea-perego** [comment]
> [...]
> 
> Redirections from http://data.europa.eu/930/* to http://uri.semic.eu/geodcatap/* are in progress.

Thanks a lot, @bertvannuffelen & @ODP-hil . I see that now it works. However, it redirects to a specific version of GeoDCAT-AP (2.0.0), whereas it should point to the unversioned URL, which always returns the latest version - i.e.:

https://semiceu.github.io/GeoDCAT-AP/releases/

**Comment by andrea-perego** [comment]
> > [...]
> > Redirections from http://data.europa.eu/930/* to http://uri.semic.eu/geodcatap/* are in progress.
> 
> Thanks a lot, @bertvannuffelen & @ODP-hil . I see that now it works. However, it redirects to a specific version of GeoDCAT-AP (2.0.0), whereas it should point to the unversioned URL, which always returns the latest version - i.e.:
> 
> https://semiceu.github.io/GeoDCAT-AP/releases/

@bertvannuffelen , this problem has not been fixed, so better re-open this issue.

**Comment by bertvannuffelen** [comment]
It should be life now.

**Comment by andrea-perego** [comment]
> It should be life now.

Yes, thanks, @bertvannuffelen .
