### ISSUE TITLE
DCAT-AP_2.1.0.rdf raises input error

### ISSUE THREAD

**Issue by coolharsh55** [SEMICeu/DCAT-AP#222]
Loading https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.1.0/dcat-ap_2.1.0.rdf produces an error regarding invalid input. I could not discern the exact cause as there seem to be missing elements. The JSON-LD serialisation https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.1.0/dcat-ap_2.1.0.jsonld also returns an empty graph due to only containing context (declarations). The previous release (2.0.1 https://github.com/SEMICeu/DCAT-AP/tree/master/releases/2.0.1) has no such issues.

**Comment by bertvannuffelen** [comment]
@coolharsh55 thank you for spotting the RDF parsing error. I addressed the RDF representation in a new bugfix draft. It missed a closing tag.

For the jsonld: this is only a context indeed. So I am not sure what is the error you point to.

**Comment by coolharsh55** [comment]
Thank you. Re. JSON-LD, I meant to say that the error isn't present or evident, so I wasn't certain where the origin of the error was.
