### ISSUE TITLE
Shacl rule for owl:versionInfo too restrictive, allows only one versionInfo

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#225]
The following rule restrictes the number of owl:versionInfo to 1:

```
:Dataset_Property_owl_versionInfo
    sh:maxCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path owl:versionInfo ;
    sh:severity sh:Violation .
```

In theory, this would be a problem, if someone wants to provide owl:versionInfo in multiple languages.
I think we should use [`sh:uniqueLang`](https://www.w3.org/TR/shacl/#UniqueLangConstraintComponent) for this:

```
:Dataset_Property_owl_versionInfo
    sh:uniqueLang true ;
    sh:nodeKind sh:Literal ;
    sh:path owl:versionInfo ;
    sh:severity sh:Violation .
```

**Comment by bertvannuffelen** [comment]
This is actually a specification change, 

It seems like one with a low impact. But lets investigate the case:

The current usage note is "This property contains a version number or other version designation of the Dataset.".

My question based on this usage note is that the usage note seems to suggest a technical representation of the version, which somehow is language neutral. While you seem to refer to maybe some more descriptive text as value.
I think that is the underlying reason for the max-cardinatity of 1 and not unique in the language.

**Comment by init-dcat-ap-de** [comment]
Thank you for the clarification. It seems like I thought about `adms:versionNotes` when writing the issue. 
But `adms:versionNotes` already has the cardinality of `*`.

In my opinion this issue can be closed.
