### ISSUE TITLE
Use OP Distribution Status NAL for adms:status of Distribution as controlled vocabulary to be used

### ISSUE THREAD

**Issue by H-a-g-L** [SEMICeu/DCAT-AP#228]
DCAT-AP lists [ADMS Status vocabulary](http://purl.org/adms/status/) to be used with `adms:status` (domain dcat:Distribution). Considering issues raised with the list (cfr. https://github.com/SEMICeu/DCAT-AP/issues/86 and https://github.com/SEMICeu/DCAT-AP/issues/211), the EU-Vocabularies team of Publications Office has just published the new [distribution-status](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/distribution-status) Named Authority List. The list includes all terms from the ADMS vocabulary which are encoded as `skos:exactMatch` of the corresponding NAL terms (cfr. https://publications.europa.eu/resource/authority/distribution-status/DEPRECATED). 
It is therefore suggested to replace the recommended vocabulary with the OP one. The benefits of using the OP Controlled Vocabulary include the addition of `skos:definition`, multi-lingual `skos:prefLabel`s and dereferenceable URIs.

**Comment by init-dcat-ap-de** [comment]
**Solution Summary:** 
Use of [EU Vocabularies Distribution Status](http://publications.europa.eu/resource/dataset/distribution-status) for `adms:status`.

https://semiceu.github.io/DCAT-AP/releases/3.0.0/#controlled-vocabularies-to-be-used
![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/8a49a1fd-5e79-4d0e-bbc1-800f129940af)

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de, what is the issue you like to highlight? It seems I am overlooking the issue you report.

**Comment by init-dcat-ap-de** [comment]
@bertvannuffelen, I was only summarizing the changes in 3.0 regarding this issue. In this case, I have no problem with this solution ;-)

**Comment by init-dcat-ap-de** [comment]
Since the ticket is still open, I would like to point out the unusual usage note: All possible specifications are mentioned here (as labels, not the URIs to be used), which is never done otherwise.

It seems to me to be a holdover from version 2.1, when the values were "hidden" in the ADMS ontology.

![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/20269047-a190-44ea-a306-b30f567b1dbe)
