### ISSUE TITLE
Context Statement Chapter 1.1 could be fleshed out more into a purpose statement

### ISSUE THREAD

**Issue by sabinem** [SEMICeu/DCAT-AP#237]
What I am missing in DCAT-AP is a more fleshed out purpose statement that helps with understanding and decision making 

What I understood so far is that DCAT and DCAT-AP are about making data findable and thus reusable. 
That is a goal, but it is still a bit vague to me: I would like to have something more measurable in this regard. 

For example when I go on the European dataportal and find a dataset, that might be interesting to me, I am able to download the data but the URI points to a URI of that dataset on the European data portal. I have no owl:sameAs, that hints me on which other dataportal the dataset can be found on and I have no information about what metadata was added in which aggregation step: 

- some metadata came from the original data publisher
- the dataset was most likely harvested by and then again harvested from a national data portal, that added additional metadata
- the european dataportal added even more additional metadata about metadata and data quality and about similar datasets

Initially I thought that the goal was to get back to the dataset at the original publisher, but that is mostly not possible. 
Provenance is also not of interest here since the datasets are not really derived from each other. The goal is to make data findable. 

From the standpoint of data reuse: reuse needs
- license information
- understanding of the data structure or service structure
- knowledge of a trustworthy publisher
- knowledge of availability
- knowledge of versioning and change policies (how do I know when the data structure changes)

I am not sure whether my issue makes sense, it is just something that I miss as a guidance in how make portals DCAT-AP conformant and whether or not it needs national DCAT application profiles.

Thanks in advance for any thoughts and answers regarding this matter.

**Comment by bertvannuffelen** [comment]
More context is provided. But it will be a continuous process to further improve and keep those sections up to date.
