### ISSUE TITLE
Versioning in DCAT 3.0

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#241]
<html>
<body>
<a class="CID692704ae-f8e0-4545-b9be-1b0c85465b98" data-sessionid="81cb3779-f884-89c5-f924-1e084283d7df" data-shapeids="4" data-slideid="" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </a><div style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Property​ | DCAT 3.0​ | DCAT-AP 2.1.1​ | Proposal​
-- | -- | -- | --
Previous version​ | Dcat:previousVersion​ | ​ | Adopt as there is no counterpart in DCAT-AP​
Has current version​ | Dcat:hasCurrentVersion​ | ​ | Adopt as there is no counterpart in DCAT-AP​
Has version​Is version of​ | Dcat:hasVersion​dcat:isVersionOf​ | Dct:hasVersion​dct:isVersionOf​ | Deprecation of the old URI mapping and replace it with the new URIs. ​Create supporting SHACL shape to detect deprecated URI usage​
version​ | Dcat:version​ | Owl:versionInfo​ | Deprecation of the old URI mapping and replace it with the new URIs. ​Create supporting SHACL shape to detect deprecated URI usage​​
Version Notes​ | Adms:versionNotes​ | Adms:versionNotes​ | Adopt as is​

</div>
</body>
</html>

**Comment by bertvannuffelen** [comment]
See also #203.

**Comment by init-dcat-ap-de** [comment]
This list seems to miss `[dcat:version](http://www.w3.org/ns/dcat#version)`.

These attributes are on the class `dcat:Resource`, so we have to decide, which sub-classes explicitly inherit them.
At a minimum: `dcat:Dataset`. But what about `dcat:DatasetSeries`, `dcat:Catalog` or `dcat:DataService`?

**Comment by init-dcat-ap-de** [comment]
Property             | planned in DCAT-AP 3.0     | V 17 July 2023 in...
-------------------- | ------------------------- | --------------------- 
Previous version     | `dcat:previousVersion`    | missing?
Has current version  | `dcat:hasCurrentVersion`  | missing?
Has version          | `dcat:hasVersion`         | [Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.hasversion)
Is version of        | `dcat:isVersionOf`        | [Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.isversionof)
Version              | `dcat:version`            | [Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.version)
Version Notes        | `adms:versionNotes`       | [Dataset](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.versionnotes)

~ ~ ~

**Solution Summary:** 
As described in post 1. Attributes are only planned for `dcat:Dataset`.

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de unless there are explicit needs to make a statement about these properties they are considered as optional properties according to the semantics described in the DCAT 3.0 specification. 

Since no specific requests have been made, only the existing DCAT-AP properties in the previous release 2.x that are impacted by this table have been adjusted to align with DCAT 3.0.

**Comment by bertvannuffelen** [comment]
A final note to this topic: we will only include the properties that are not subject to the W3C inverse property guidelines.

**Comment by fabian-santi** [comment]
Hello @bertvannuffelen ,

I was tying to understand why Dcat:previousVersion​ was not included as an optional field in DCAT-AP 3 but was not able to find an explicit explanation for it here.

I am working on DCAT-AP-CH 3 and the question popped up as it seems to be a useful property for our catalog. Would you be able to give us an explanation as to why it was not included, and mavbe the downsides if we were to include it in DCAT-AP-CH 3?
