### ISSUE TITLE
dcat:Distribution - remove dct:conformsTo?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#25]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:conformsTo:
•	Usage: near 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.
There is a [discussion](https://github.com/w3c/dxwg/issues/55) at the Dataset Exchange Working Group around the requirement to "_Define a way to include identification of the schema the described data conforms to_". A future version of DCAT-AP should take into account a resolution of the issue by DXWG.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by jakubklimek** [comment]
I am strongly against removing `dct:conformsTo` for the following reasons:

1. The argument with the property not being used in EDP seems invalid to me. EDP harvests the data mainly from legacy CKAN APIs, which have no support for this property, and only then converts it to DCAT-AP - hence the missing property.
2. It is the only way of connecting a distribution to a schema, which is a crucial piece of information.
3. We use this property extensively in the [Czech National Open Data portal](https://data.gov.cz/english/), which has a native [DCAT-AP dump](http://data.gov.cz/soubor/nkod.trig). It is harvested to EDP via its [SPARQL endpoint](https://data.gov.cz/sparql) and, to my best knowledge, is the only one (or at least one of few) harvested this way so far. The harvested datasets such as [this one](https://www.europeandataportal.eu/data/en/dataset/https-nkod-opendata-cz-zdroj-datova-sada-244102998/resource/5569f4d8-7ba2-445d-8c2b-e8606cd87ea9) use the property.

**Comment by makxdekkers** [comment]
Very good points, @jakubklimek.

**Comment by addragan** [comment]
Issue rejected due to disagreement comments. The issue will be closed with no changes in the specification.
