### ISSUE TITLE
HVD C1.  Being part of HVD scope

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#251]
The HVD defines 6 thematic data categories: 
geospatial; earth observation and environment; meteorological; statistics; companies and company ownership; mobility

**Proposal:**
Create new property m8g:hvdCategory defining the HDV category to which this resource belongs.
The codelist will be created and maintained by the Publications Office.
A resource may belong to more than one data category

**Comment by bertvannuffelen** [comment]
In https://github.com/SEMICeu/DCAT-AP/issues/231#issuecomment-1317163139 a single, data category agnostic,  indicator was proposed. 

The above proposal C1 addresses at the same time the proposal from the comment as the need to know in which HVD data category the dataset is associated.

**Comment by anarosa-es** [comment]
What about to create a sub-class "High Value Dataset"? It can add any property and relationship specific to HVD

**Comment by jakubklimek** [comment]
@anarosa-es please see https://github.com/SEMICeu/DCAT-AP/issues/231#issuecomment-1327339254 for the discussion on this topic

**Comment by bertvannuffelen** [comment]
I want to raise attention that in all rules discussed are to be read as: _The rule is applicable when the dataset is subject to the HVD regulation._ 

It means that if you have a dataset, or a distribution or an API that is not subject to the regulation, you should not indicate it is subject to the HVD regulation. 
But inversely, if the dataset is part of the HVD regulation and the MS wants to report about this in DCAT-AP, then these rules should be followed.

MS have the ability according to the HVD regulation not use DCAT-AP as unique metadata format for HVD. But in the end the reporting should be provided in that case and then all metadata requirements expressed in the regulation should be fulfilled.  
A MS could take benefit from having all metadata in a single metadata format represented to easy the followup and reporting, but that is not a requirement of the HVD regulation. As DCAT-AP is cross domain, the likelihood that the reporting requirements can be realized from this approach.

**Comment by sirex** [comment]
In order to ensure, that a dataset and all distributions of a datasets are HVD compliant, I would use existing ways, to define relationship between a dataset and other resources:

https://www.w3.org/TR/vocab-dcat-3/#qualified-relationship

That means, if I have a dataset "Addresses", then I could create a derived version of that dataset, fully compatible with HVD requirements, while leaving original "Addresses" dataset, containing distributions, that are not HVD compliant.

Basically there would be a hierarchy of datasets:

```
`- Official national register for addresses (not open data)
    |- Addresses (random, poor quality open CSV files, published somewere)
    |- Addresses (HVD compliant data)
    `- Addresses by region (Data Series, another publication of same data, but in a different data organization)
      |- Addresses of Region 1
      `- Addresses of Region 2
```

This way, we will know the origin of all the datasets and each dataset could be tuned for different uses cases or regulations.

So this way, if a dataset is tagged as HVD, all distributions of that dataset MUST also be HVD compliant without explicit tagging.

If a HVD dataset contains non HVD distributions, then a new dataset should be created to split distributions into HVD and non HVD.

**Comment by bertvannuffelen** [comment]
@sirex  The Qualified Relationship is an option for encoding a related network of entities. 

You also suggest to apply implicit assumptions on compliance. Personally, I am reluctant for this, as I have the feeling it is not a general case.
Secondly, my reluctance comes from that the legislation might impose just a little requirement (e..g. a bulk download with an open licence). If the implicit rule would make all other distributions also in scope of the legislation, then this might be non-intented side-effect of the interpretation. A too wide interpretation potential is a risk: it might give users a false impression.

**Comment by sirex** [comment]
My suggestion, to use explicit HVD tagging only on datasets, and if dataset is tagged as HVD, then all distributions of that dataset MUST be also HVD compliant.

If a HVD dataset has some distributions, that are not HVD compliant, then such distribution, should be split into two distributions, where one contains only HVD compliant distributions and another, all other non HVD compliant distributions.

So I think, this is still pretty explicit and can be validated automatically. Also, this would help to separate concerns, dataset defines scope and distribution, MUST fit into the scope defined by a dataset. So if dataset declares, that this is a HVD dataset, then any non HVD distributions, can't be part of this dataset and must be published as port of another, non HVD dataset.

**Comment by bertvannuffelen** [comment]
>
> If a HVD dataset has some distributions, that are not HVD compliant, then such distribution, should be split into two distributions, where one contains only HVD compliant distributions and another, all other non HVD compliant distributions.
> 
>

Do you mean _'split in two datasets'_  instead of _'split into two distributions'_ ?

Personally I tend to avoid such rules, because the more complex metadata structuring rules there are the more difficult it is to maintain them, and to have them created. 

From an end-user perspective, having 3 datasets in your portal called: 'Addresses', 'Addresses HVD and ''Addresses INSPIRE'  are confusing.  Is there a difference between them? Are they connected? Which one to use? 
Let's leave this choice open for the implementers; as each portal has it "deduplication" rules,  it is hard to impose universal one. This avoids to introduce specific DCAT-AP HVD deduplication rules.  

While I understand your rule for distributions (file dumps) there is a similar case to be made for APIs: in many geospatial domains a single data service (API) is used to serve many datasets (each layer is a different dataset). How do you deal with that? Should a API only serve HVD datasets? Or can it be mixed? 
If we follow the splitting rule, you impose a change to the INSPIRE community, which should be accepted by them. 
We cannot impose a rule in DCAT-AP HVD that is violated by an accepted practice in a specific domain, unless the HVD forces a specific interpretation (e.g. URIs for licence information).   

(Ps. Note: if this splitting eases your portal management and HVD reporting management, then you can still create a MS specific rule.)

**Comment by sirex** [comment]
> Create new property m8g:hvdCategory defining the HDV category to which this resource belongs.

What is `m8g`?

Why a new property is needed instead of using [dcat:theme](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_theme)?

**Comment by jakubklimek** [comment]
`m8g` is the namespace used by the Core Vocabularies.

`dcat:theme` could be used as well, but there the HVD categories would be mixed with other themes and you would need additional data (the IRI of the ConceptScheme (`skos:inScheme` of the concept)) to know that it is an HVD category. A new property would make this distinction more obvious and without the need to download/duplicate external data - the HVD category codelist.

**Comment by bertvannuffelen** [comment]
To summarize the DCAT-AP HVD approach:

- use r5r:applicableLegislation to denote if a resource (e.g. dataset) is within scope of the HVD IR by providing a reference to the HVD IR ELI.
- use r5r:hvdCategory to denote the (toplevel) category as named in the HVD IR.

It is an additive approach to existing metadata.

**Comment by jakubklimek** [comment]
@bertvannuffelen I did not find anywhere the reason why the controlled vocabulary used with r5r:hvdCategory only contains the 6 toplevel categories and not the lower level consisting of "datasets in scope" such as "Weather alerts" or "Radar data".

Those are identified in the HVD IR Annex and therefore could be used to improve search for e.g. "Weather alerts" from the EU. Or is there any other way to easily facilitate such search?

**Comment by bertvannuffelen** [comment]
@jakubklimek today the HVD data categories are more to provide a link with the specific HVD IR requirements rather than an enumeration of specific datasets. 

There is no complete enumeration of specific datasets:  those dataset names in the IR are more indications of the scope rather than imitative and precisely naming. 

Your example works for meteorological domain, while for the Earth Observation and Environment domain this is just a list of themes and articles in legislation.

The HVD category has not the intent to harmonise dataset names or to group them for higher findability. It is more a policy mean to ensure that datasets are maintained on a higher quality according to the best practices in each domain. 
That is the reason why there is such diversity in the detailed level.

Nevertheless it might be an outcome of the implementation of HVD that "similar datasets" across Europe, get similar tagging/naming. For instance, if there is within the domain of meteo the agreement that the data collection method (radar, weather station, public sources) is expressed as a keyword (or better as a subject), then portal software could lead users easily to other data that is HVD and using the same data collection method.
Instead of creating yet another subcategory my suggestion would be that publishers of HVD datasets should invest in publishing the most precise and quality metadata  That focus will have more impact I believe.

**Comment by jakubklimek** [comment]
@bertvannuffelen Thanks for the explanation. So if I understand it correctly, you suggest to leave to the individual domains to establish their own controlled vocabularies of themes in their domains? Do you know if in any of those domains, such activities are on-going? Or is the intention to leave this open-ended for, let's say a couple of years, and then re-visit the topic once we actually have some HVDs published?
