### ISSUE TITLE
HVD C4. Bulk download

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#254]
The HVD implementing regulation requires to provide bulk downloads for datasets.
Bulk download is a functionality that allows to get the whole dataset as a copy on your local computer.

**proposal**

As in DCAT-AP guidelines is specified, a downloadable file is to be represented with a Distribution.

**Comment by sirex** [comment]
As I understand Bulk download requirement mostly applies to Data Services, because Data Services might provide row by row access to data, but not Bulk download.

If we have:

```ttl
ex:dataset1 a dcat:Dataset ;
  dcat:distribution ex:dist1 .

ex:service1 a dcat:DataService ;
  dcat:servesDataset ex:dataset1 .

ex:dist1 a dcat:Distribution ;
  dcat:accessService ex:service1 .
```

and `ex:service1` does not support Bluk download. Then how we can tell, that `ex:dist1` has a single downloadable file?

**Comment by jakubklimek** [comment]
@sirex I view the requirement basically as having both a dataservice and a downloadable file as distributions of a HVD dataset:
```turtle
ex:dataset1 a dcat:Dataset ;
  dcat:distribution ex:dist1 , ex:dist2 .

ex:dist1 a dcat:Distribution ;
  dcat:accessService ex:service1 .

ex:service1 a dcat:DataService ;
  dcat:servesDataset ex:dataset1 .

ex:dist2 a dcat:Distribution ;
  dcat:accessURL <file> ;
  dcat:downloadURL <file> .

```

**Comment by bertvannuffelen** [comment]
The feedback from @jakubklimek is correct. 

In case the dataset is subject to the HVD IR, and the HVD IR mandates the presence of a bulk download (almost always the case), then the downloadURL is mandatory.
