### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by mortenwh** [SEMICeu/DCAT-AP#268]
Do you have a pdf of this as well?

**Comment by makxdekkers** [comment]
You should be able to Print-to-PDF from your browser.

**Comment by bertvannuffelen** [comment]
Since the publication as html (public online representation)  is more in line with the  publication as semantical data specification, a separate pdf version is not created anymore.
As Makx mentioned from now on we rely on browser extensions to support these needs.

**Comment by mortenwh** [comment]
Fair enough - I just wanted to have a way to add notes when I read it. I'll print-to-pdf :)
