### ISSUE TITLE
dcat:Distribution - remove adms:sample?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#27]
The DCAT-AP usage analysis on the European Data Portal showed the following:

adms:sample
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by DGatt** [comment]
Samples are of interest mostly if
a) the data is not available as open data or
b) only available as a bulk download, so large that it creates bandwidth/time issues

Both situations are not desirable in open data situations. On the other hand, German statistical data is often presented with the opportunity to download a completely empty table. This is similar but less formal to the case of a specification to which the datasets adheres to in its structure (this can be captured in Dataset - dct:conformsTo), and can be helpful in planning automated processing of the data (for example an xml or json schema could be referenced here). So I would argue to replace  the property with one with a more relaxed use case/definition and range (rdfs:resource).

**Comment by makxdekkers** [comment]
The property adms:sample is not included in the properties for dcat:Distribution in the profile. Please refer to https://github.com/SEMICeu/DCAT-AP/issues/10 for the discussion.
