### ISSUE TITLE
New class DataServiceRun

### ISSUE THREAD

**Issue by albertoabellagarcia** [SEMICeu/DCAT-AP#271]
This class represent the execution of a dataservice. It is suggested by users and already implemented. More information can be found at the smart data models in this [link](https://github.com/smart-data-models/dataModel.DCAT-AP/blob/master/DataServiceRun) and the specification is [here](https://github.com/smart-data-models/dataModel.DCAT-AP/blob/master/DataServiceRun/doc/spec.md). Examples of the use of this entity are [here](https://github.com/smart-data-models/dataModel.DCAT-AP/tree/master/DataServiceRun/examples).

**Comment by bertvannuffelen** [comment]
@albertoabellagarcia I am not sure what is the business case behind this class? 

I do not understand the class. Can you explain what it represents? Can you provide a storyline in which the class features?

**Comment by bertvannuffelen** [comment]
Unless there comes more suggestions and feedback that this issue could progress. The proposal is to close the issue with the release 3.0.0
