### ISSUE TITLE
Clarify if dataset series is allowed to contain other dataset series

### ISSUE THREAD

**Issue by matthiaspalmer** [SEMICeu/DCAT-AP#275]
How should the statement "tree organised structures are not prohibited" in chapter 18 be interpreted? Is the intention that dataset series are allowed to contain other dataset series?
Clearly this is allowed in DCAT as dcat:DatasetSeries is a subclass of dcat:Dataset. However, we believe that allowing it in DCAT-AP3 is another matter.

If this is the case that it is allowed it should be stated much more clearly higher up in the specification as it will affect both portal implementations and editing software complying to DCAT-AP3.

**Comment by jakubklimek** [comment]
In the webinar, a discussion about how theoretical this case is, was held. I just want to emphasize that in Czechia, it is already used in practice, e.g. for topical dataset series, i.e. to group data from a certain IT system, which includes datasets and a temporal data series.

And I can also see a combination of spatial and temporal series represented this way, i.e. a temporal series of budgets, containing spatial series for budgets in municipalities e.g. in that year. So the top level series is years, the lower level series is municipalities in that year.

**Comment by bertvannuffelen** [comment]
In the Webinar 21 Nov 2023, it was decided to not restrict the use of Dataset Series.
