### ISSUE TITLE
Avoid having too many datasets in a dataset series

### ISSUE THREAD

**Issue by matthiaspalmer** [SEMICeu/DCAT-AP#276]
It is highly likely that dataportals will make the assumption that the amount of datasets in a dataset series can be listed directly (that there are quite few of them). That means that there won't be a searchable UI to find datasets inside a dataset series.  This assumption is supported by scenarios like one datasets is added to a dataset series per year. It should be stated if this assumption is wrong at least via an example. 

We believe this assumption should be supported by the specification by providing guidance on how to solve situations where there is a drift towards providing many more datasets in a series. For example:

If you find that you need to create hundreds of datasets in a dataset series it would be a better choice to consider other strategies, e.g.:

1. Providing downloadable files as a single distribution that point to a Web accessible folder or a zip file.
2. Provide access via a data service.
3. Introduce a hierarchy of data series

Note that dataportals will likely hide datasets that are part of dataset series and only give access via their dataset series.

**Comment by jakubklimek** [comment]
For example, the Czech catalog presumes there can be a large number of datasets in the series and has a search functionality through the members (basically, it filters all datasets for the ones in the series and re-uses the normal faceted search functionality).

So, I would say it should be expected that there can be as many datasets in a series as there are datasets in a catalog.

**Comment by jakubklimek** [comment]
Actually, I don't see dataset series handled by data.europa.eu at all, for example [this dataset series](https://data.europa.eu/data/datasets/https-opendata-mfcr-cz-lod-katalog-ares-administrativni-registr-ekonomickych-subjektu?locale=en) looks like an empty dataset 🤷🏻‍♂️

**Comment by bertvannuffelen** [comment]
So far there are no restrictions on the size or organisation of DatasetSeries. 
Also the community has not requested a specific restriction that must be followed.

So unless there are specific requests I would not restrict sizes.

**Comment by bertvannuffelen** [comment]
During webinar 21 Nov 2023 the working group agreed to not impose any restrictions.
