### ISSUE TITLE
Discourage the use of ordering properties for non-ordered datasets

### ISSUE THREAD

**Issue by matthiaspalmer** [SEMICeu/DCAT-AP#277]
For temporal datasets in a dataset series it may be interesting to point to the first and last datasets from the dataset series as well as indicate the order between datasets via dcat:prev and dcat:next.

However, if the dataset series is a geographical or another type of series (topical) that does not correspond to a linear order these properties should be discouraged.

**Comment by bertvannuffelen** [comment]
Is your proposal to not use first or last at all? 

E.g. for geospatial one could organise the dataset series according to the acronym of the country. In that case the order is always the same.

I can agree that the need for first or last is less mandatory than is seems and that one only should mandate the use of a dcat:inSeries. But if a publisher wants to organise the collection, I would say: lets honour his/hers effort.
