### ISSUE TITLE
dcat:Distribution - remove foaf:page?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#28]
The DCAT-AP usage analysis on the European Data Portal showed the following:

foaf:page:
•	Usage: 0%
•	Should these properties be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove foaf:page from Distribution.

**Comment by NatasaSofou** [comment]
It is proposed to keep it in the model for now.
