### ISSUE TITLE
HVD: Dataset series not included?

### ISSUE THREAD

**Issue by matthiaspalmer** [SEMICeu/DCAT-AP#280]
Dataset series are not included which raises the question if the recommendation extends DCAT-AP version 2 or 3?

**Comment by jakubklimek** [comment]
From the branch name and the URL (`https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/`) I think it is clear that [DCAT-AP HVD](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/) extends DCAT-AP 2, no?
![image](https://github.com/SEMICeu/DCAT-AP/assets/718827/7d078ecc-1055-4c19-a35b-156536202847)

**Comment by matthiaspalmer** [comment]
Yes, that is my guess to, but explicitly mentioned would be nice.

Also, it would be nice if it is expressed how to interpret the specification in relation to DCAT-AP 2.
I would expect something like "Properties from DCAT-AP-2 are allowed, when properties are explicitly mentioned they are either new or there is a need to discuss them in the context of HVD." 

However, I see examples where the above rule does not seem to apply, e.g. most properties under dcat:Dataservice seem to be repeated for no obvious reason. To take an example: why is dcterms:title mentioned on dcatDataservice but not for dcat:Dataset.

**Comment by bertvannuffelen** [comment]
To add to the question: in HVD IR there is no mentioning of Dataset Series. 
Thus all constraints that are expressed in the annex DCAT-AP HVD apply to DCAT-AP 2.x and DCAT-AP 3.x.
It is also the goal that the annex should be stable and natural follow the improvements made to DCAT-AP. 

To illustrate the impact of changes:
For instance adding DatasetSeries to DCAT-AP 2 to become DCAT-AP 3 has no impact on DCAT-AP HVD. 
Making a property (e.g. a creator) mandatory for a Dataset would impose additional work, however the fact this is not implemented will have no impact on the HVD compliance. It only would make the metadata more rich.
However, removing Contact Point from DCAT-AP would create troubles as HVD relies on contact information. 

The objective is to express DCAT-AP HVD in such a way that is editorally is stable as long as possible even when DCAT-AP changes. But it is our SEMIC editor duty to assess each request for impact.

**Comment by bertvannuffelen** [comment]
We will improve the release notes and dependency notes to make that clear. Today DCAT-AP HVD is an annex to DCAT-AP 2.x and the draft of DCAT-AP 3.0.
