### ISSUE TITLE
Restrictive multiplicity of conformsTo of CatalogRecord

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#284]
If I want to indicate that my catalog records conform to DCAT-AP 3.0.0 and DCAT-AP-HVD, I would need a `0..*` multiplicity for `dcterms:conformsTo` (application profile) while now it is restricted to `0..1`.

**Comment by PwC-Arthur** [comment]
![image](https://github.com/SEMICeu/DCAT-AP/assets/145554476/0f689f79-4f93-4fac-aac7-473ba44043de)

Please be informed of the SEMIC proposition related to this issue.

**SEMIC proposition:** Lift the cardinality.

We invite you to comment your approval of, or engage in discussions regarding this proposition.
