### ISSUE TITLE
HVD: Dataset, Distribution, Data Service: HVD category

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#287]
_(created on behalf of EU MS Hungary, received via e-mail)_

We are unable to find the relevant values of the field. The values should be as following:
•	Geospatial
•	Earth observation and environment
•	Meteorological
•	Statistics
•	Mobility
•	Companies and company ownership
Other values are expected to be included in the list?

**Comment by bertvannuffelen** [comment]
The toplevel categories are published here: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/high-value-dataset-category

**Comment by jakubklimek** [comment]
@bertvannuffelen The category IRIs are not dereferencable, e.g. http://data.europa.eu/bna/c_164e0bf5 - is this going to be solved by the data.europa.eu team?
