### ISSUE TITLE
dcat:CatalogRecord - remove dct:conformsTo?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#29]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:conformsTo:
- Usage: 0%
- Should this property be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:conformsTo from CatalogRecord.

**Comment by andrea-perego** [comment]
Note that GeoDCAT-AP makes use of this property. We need to check if removing it from DCAT-AP would require a revision of GeoDCAT-AP.

**Comment by NatasaSofou** [comment]
It is proposed to keep it in the model for now as property dct:conformsTo from dcat:CatalogRecord is also used in GeoDCAT-AP.
