### ISSUE TITLE
Too narrow definitions for Catalogue and Catalogue Record

### ISSUE THREAD

**Issue by terjesyl** [SEMICeu/DCAT-AP#297]
We think the following definitions are too narrow

## 7.2 Definition and Usage note of the property “themes”: 
Current value: “A knowledge organization system used to classify the Catalogue's Datasets.” 
Comment: What about the other resources that are Catalogued in the Catalogue (DataServices, DatasetSeries)? 
Change to “A knowledge organization system used to classify the Resources that are in the Catalogue.” 

The Usage note is similarly too narrow.   

## 7.3 Definition of the class Catalogue Record
Current value: “A description of a Dataset’s entry in the Catalogue.” 
Comment: A Catalogue may contain not only Datasets, but also Data Services etc. 
Change to: “A description of a Catalogued Resource’s entry in the Catalogue.”   

## 7.3 Definition of the property “application profile” 
Current value: “An Application Profile that the Dataset’s metadata conforms to.” 
Comment: A Catalogue may contain not only Datasets, but also Data Services etc. 
Change to: “An Application Profile that the Catalogued Resource’s metadata conforms to.” 

## 7.3 Definition of the property “language”
Current value: “A language used in the textual metadata describing titles, descriptions, etc. of the Dataset.” 
Comment: A Catalogue may contain not only Datasets, but also Data Services etc. 
Change to: “A language used in the textual metadata describing titles, descriptions, etc. of the Catalogued Resource.” 

## 7.3 Definition of the property “listing data” 
Current value: “The date on which the description of the Dataset was included in the Catalogue.” 
Comment: A Catalogue may contain not only Datasets, but also Data Services etc.
Change to: “The date on which the description of the Resource was included in the Catalogue.”

**Comment by christinhenzen** [comment]
+1 for changing "dataset" to "resource" (or "data" that we use as a catch-up term for datasets and other resources
