### ISSUE TITLE
Clarify properties in 7.8 Dataset member of a Dataset Series

### ISSUE THREAD

**Issue by terjesyl** [SEMICeu/DCAT-AP#298]
The definition of `previous` uses the term "Resources" implying that the property can be used with other Resources than Dataset.
In addition the usage note only mentions Datasets.

Suggestion: rewrite definition of `previous` to "The previous dataset (before the current one) in an ordered collection or series of resources."

In addition the usage note is a bit confusing: "Unless the dataset is the last in the chain a dataset in a collection must have a previous one." Here `last in chain` = `first in series`. And only the last element in the chain is missing `dcat:prev` (going against the intuition that it is the first item in a linked list that has no `previous` link).

Suggestion: rewrite usage note to ""A dataset in a collection must have a previous one unless it is the first in the series""

**Comment by matthiaspalmer** [comment]
Be careful with the wording in the usage note, since not all dataset series are ordered (e.g. geographical or topical) there should be not be a hard requirement to express `dcat:previous`. See #277.

**Comment by bertvannuffelen** [comment]
During the webinars of 21 Nov 2023 and 16 jan 2024, the working group decided to include only the minimal aspects of a Dataset Series in DCAT-AP. Therefore the ordening properties are disappeared.
