### ISSUE TITLE
Definition of Agent type

### ISSUE THREAD

**Issue by oystein-asnes** [SEMICeu/DCAT-AP#299]
The current definition of [Agent type](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Agent) “A type of the agent that makes the Catalogue or Dataset available.” neglects the fact that an Agent is also used for dct:creator. In addition comes the question raised in #289  whether Dataset Series is a subclass of Resource or Dataset

Proposal:  Change to "A type of the agent"

**Comment by bertvannuffelen** [comment]
The suggestion of the definition makes the definition entirely circular. We will look for a new definition, one which does not rely on the word "type".

**Comment by PwC-Arthur** [comment]
![image](https://github.com/SEMICeu/DCAT-AP/assets/145554476/6ea80bbf-7acd-4ac1-8f6b-2be9cdf41bd6)

Please be informed of the SEMIC proposition related this issue.

**SEMIC proposition:** Change definition to: "the nature of the agent".

We invite you to comment your approval of, or engage in discussions regarding this proposition.

This issue has two parts, the proposition concerning the second part can be found under issue [#320](https://github.com/SEMICeu/DCAT-AP/issues/320).
