### ISSUE TITLE
dcat:Catalog - dct:spatial recommended?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#3]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:spatial
•	Usage: 83.75% with almost all countries represented
•	Should this property be made recommended?

**Comment by makxdekkers** [comment]
If there is no strong support for making this property recommended, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Make dct:spatial recommended for Catalog.

**Comment by bertvannuffelen** [comment]
And what will be the value?

a value from a codelist, a geometry?

I think first the definition of dct:spatial should be made more precise.

Does it means that "all data in the catalog applies to the spatial boundaries" or "all data in the catalog are somehow connected to the legal entity that has a spatial location".

Usecase: I have a dataset `embassy` of all embassies of Belgium. 
If `<data.gov.be/catalog> dct:spacial dbpedia:Belgium` is stated then can the dataset `embassy` be part of the catalog?
if `<data.gov.be/catalog> dct:spacial "WKT POLYLINE (....) " ` is stated then can the dataset `embassy` be part of the catalog?

If it becomes a recommendation then I propose first to make the definition more precise.

**Comment by addragan** [comment]
Proposed resolution: Make dct:spatial recommended for Catalog and agree on a more precise definition of the property.
