### ISSUE TITLE
dcat:CatalogRecord - remove dct:title?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#30]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:title:
- Usage: 0%
- Should this property be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:title from CatalogRecord.

**Comment by NatasaSofou** [comment]
It is proposed to keep it in the model for now.
