### ISSUE TITLE
Add chapter on inverse properties?

### ISSUE THREAD

**Issue by terjesyl** [SEMICeu/DCAT-AP#300]
Given that `dcat:next` and `dcat:seriesMember` have been introduced, would it be worth adding a chapter similar to the DCAT chapter [Use of inverse properties](https://www.w3.org/TR/vocab-dcat-3/#inverse-properties) ? Especially important is the requirement that inverses *"MAY be used only in addition to [its property], and that they MUST NOT be used to replace them."*

These are the properties I found in DCAT-AP with inverses.

| Property | Inverse |
| - | - |
| dcat:prev | dcat:next |
| dct:hasPart | dct:isPartOf |
| dcat:hasVersion | dcat:isVersionOf |
| dcat:inSeries | dcat:seriesMember |

**Comment by bertvannuffelen** [comment]
To the community is there any preference of any of these: what is the master, what is the derived?

**Comment by terjesyl** [comment]
If there is no specific reason for doing otherwise, I suggest following DCAT here.

**Comment by matthiaspalmer** [comment]
I think we should consider use cases where also dcat:seriesMember are used as the master when dataset series are created independently from the datasets they contain, for example:

Hundreds of municipalities provide air quality datasets, all conforming to the same specification. The national environmental agency takes on the role of aggregator and creates a dataset series corresponding to all air quality measurments in the country as a whole for easy overview / access.

**Note 1:** the newly formed dataset series is expressed in a catalog and refers to datasets expressed in hundreds of different catalogs.

**Note 2:** in this scenario nothing prohibits that a dataset appears in multiple dataset series. (E.g. a regional dataset series in addition to a national.)

If we are to allow scenarios like this we cannot assume that dcat:inSeries is the master, if by that we mean that we mean that we do not consider it's inverse being present (for instance in portals).

**Comment by bertvannuffelen** [comment]
Added in https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/#inverse-properties
