### ISSUE TITLE
Definition of the property “access rights” (Dataset)

### ISSUE THREAD

**Issue by oystein-asnes** [SEMICeu/DCAT-AP#301]
Current value is: “Information that indicates whether the Dataset is open data, has access restrictions or is not public.”

10.2 (controlled vocabularies) says “Use one of the following values (:public, :restricted, :non-public)”.  `public` is defined: "Publicly accessible by everyone. Usage note: Permissible obstacles include registration and request for API keys, as long as anyone can request such registration and/or API keys."

"Publicly accessible by everyone" does not necessarily mean “open data”. (?)

Proposal: Change to “Information that indicates whether the Dataset is public, has access restrictions or is not public.”

**Comment by bertvannuffelen** [comment]
@oystein-asnes , I think this is about the semantics given to a codelist value. And it is connected with the issue #302 you also filed.

I am quite fine with the definition associated with the concept "PUBLIC". 

For me, I expect that the conclusion from an assessment whether a dataset is "Open Data" is that the access_rights gets the value PUBLIC. 
One however cannot conclude that only the datasets with access_rights are the "Open Data" datasets. There is always the possibility that one has made a mistake or not included all entries.   
And also when the value PUBLIC is provided, not interested party should encounter restrictions that would block the access. (Excluding measures to ensure well-behavior when accessing the data.).

To clarify your request: 
   a) do you want to change the definition of the concept PUBLIC
   b) do you want to change the definition of the property accessrights for Dataset.

**Comment by oystein-asnes** [comment]
If the intention with the concept PUBLIC is to indicate open data, the definitions should be changed. If not, the usage note should be aligned. 

The current definisjon of accessRights may mislead to the misunderstanding that this property alone is enough to indicate if the dataset is open data or not, while a combination of this property and dct:license is needed .

**Comment by bertvannuffelen** [comment]
In accordance with webinar of 21 Nov 2023, the definition has been adapted to "Information that indicates whether the Dataset is publicly accessible, has access restrictions or is not public." .
