### ISSUE TITLE
Incomplete list of properties in 10.2 "Controlled vocabularies to be used" ? 

### ISSUE THREAD

**Issue by oystein-asnes** [SEMICeu/DCAT-AP#304]
Are these properties intentionally excluded from chapter 10.2  "Controlled vocabularies to be used"

| Property | Comment/Question | 
| ----------| -----------------------|  
| dct:accrualPeriodicity | 	Shouldn’t this also apply to the property dct:accrualPeriodicity in the classes “Dataset member of a Dataset Series”, “Dataset Series”? | 
| dct:format | 	Shouldn’t this also apply to the property dct:format in the class “Data Service”? | 
| dct:publisher | 	Shouldn’t this also apply to the property dct:publisher in the class “Data Series”? |
| dct:spatial | 	Shouldn’t this also apply to the property dct:spatial in the class “Data Series”? | 
| adms:status | 	Shouldn’t this also apply to the property adms:status in the class “Catalogue Record”? |

**Comment by bertvannuffelen** [comment]
Address for all except for adms:status in the context of Catalogue Record. The usage is is there different than adms:status in a Distribution.  Therefore that has not been applied.
