### ISSUE TITLE
HVD: Risk of overlap for Quality of service with generic documentation on data services

### ISSUE THREAD

**Issue by matthiaspalmer** [SEMICeu/DCAT-AP#310]
At least since 1.1 there have been a `foaf:page` property on `dcat:Dataset` and `dcat:Distribution` allowing for a way to point to external documentation. Note that this is not part of DCAT, it is an addition in DCAT-AP.

With the inclusion of Data services in DCAT-AP2.0 only a few properties of all potential properties from `dcat:Resource` where included, likely in part due to lack of good use-cases and the decision to not include the intermediate class (and newly introduced).

Since some time we have argued for the inclusion of more properties on Data services, e.g. see #272. One of the properties argued to be included is foaf:page to correspond to documentation just like we have on datasets.

If this view is accepted, either now or in the future, this presents a conflict with the use of `foaf:page` for "Quality of service". Of course it could be argued that "Quality of service" is nothing more than a special case of documentation. But, since this is regulated by law we may end up in a situation where it won't be possible to distinguish if a data service complies with the HVD regulation or not if `foaf:page` is used for the wider purpose.

Hence, a suggestion would be to introduce another subproperty of foaf:page to correspond to "Quality of service", for example:
`http://data.europa.eu/r5r/qualityOfService`

**Comment by matthiaspalmer** [comment]
There is also a small typo, the link on "Quality of service" is `foaf:Page` instead of `foaf:page`.

**Comment by bertvannuffelen** [comment]
@matthiaspalmer thanks for pointing this historic reference out. 

This is yet another case where "subproperties" are to be considered.

We have roughly 2 options here:

a) we introduce a property _documentation_ (foaf:page) as generic property in DCAT-AP 3.0.0 as suggested earlier. And we specialise the usage note in DCAT-AP HVD: "also quality of service documents can be included." (So the property quality-of-service defacto disappears)

b) we introduce in HVD the subproperty to already make a distinction between different kinds of documentations.
