### ISSUE TITLE
Catalogue or Catalog?

### ISSUE THREAD

**Issue by idevisser** [SEMICeu/DCAT-AP#318]
In DCAT-AP the name of the class and property is Catalogue. In DCAT the name of what i assume the same class and property is Catalog.
Is there a differnce?

**Comment by jakubklimek** [comment]
DCAT is a W3C-based recommendation, in American English.
DCAT-AP is a European application profile and as such it uses British English.
This, of course, applies only to the human readable labels, not the class IRIs.

**Comment by idevisser** [comment]
clear, thnx!

**Comment by idevisser** [comment]
see explanation
