### ISSUE TITLE
Proposition: Publisher property Data Service (Issue #305)

### ISSUE THREAD

**Issue by PwC-Arthur** [SEMICeu/DCAT-AP#319]
![image](https://github.com/SEMICeu/DCAT-AP/assets/145554476/3393ddc3-42b4-47f7-9aa2-d466e4c96fcc)

**Comment by PwC-Arthur** [comment]
Please be informed of the SEMIC proposition related to issue [#305](https://github.com/SEMICeu/DCAT-AP/issues/305).

**SEMIC proposition:** Make _publisher_ a recommended property for Data Service.

We invite you to comment your approval of, or engage in discussions regarding this proposition.

**Comment by bertvannuffelen** [comment]
similar request is made in #272
