### ISSUE TITLE
dcat:CatalogRecord - remove dct:language?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#32]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:language:
- Usage: 0%
- Should this property be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:language from CatalogRecord.

**Comment by NatasaSofou** [comment]
It is proposed to keep it in the model for now.

**Comment by akuckartz** [comment]
Why?

**Comment by NatasaSofou** [comment]
The issue was tagged as "wont-fix"  and proposed to be closed with no changes in the specification. WG members were encouraged to review the issue. Since no comments or arguments were received, the issue is closed.
