### ISSUE TITLE
HVD: suggestion of automatically generating the report for HVD based on metadata (DCAT)

### ISSUE THREAD

**Issue by Nolfge** [SEMICeu/DCAT-AP#321]
As with the INSPIRE regulation and how it deals with monitoring and reporting, we suggest that annual reporting for the HVD could also be done by automatically generating the report based on metadata. 
Technical guidelines could be a solution so that all member states and data providers report based on the same metadata elements for uniformity. 
In Flanders we are working on the analysis to extract everything that is in the HVD regulation (determine the exact metadata elements), when we are ready we can share it with the whole community so that we can work on a fit for all.

**Comment by laers** [comment]
It sounds as a very good idea and the INSPIRE monitoring/reporting experiences based on metadata is good and well documented. 

Be aware that stand-alone ISO 19115/19139 metadata for INSPIRE **Network Services** no more is an **obligation** to provide. See https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification

So calculation of indicators for HVD-reporting can "only" be based on INSPIRE **Data Set** metadata.

**Comment by bertvannuffelen** [comment]
@Nolfge the automatic generation of the HVD reporting is one the key motivations for DCAT-AP HVD. Nevertheless, at this moment there are no concrete reporting queries included in this specification. Together with CNECT this will be explored in the future.

**Comment by bertvannuffelen** [comment]
Dear community, DG CNECT has together with the DEU and SEMIC proposed a first version on a common reporting approach using the metadata provided by the EU MS to DEU. 

The documentation shall be centralised on this page: https://dataeuropa.gitlab.io/data-provider-manual/hvd/reporting/
