### ISSUE TITLE
HVD: suggestion to introduce self-declaration to report on HVD

### ISSUE THREAD

**Issue by Nolfge** [SEMICeu/DCAT-AP#322]
We would like to introduce the suggestion of working with "self-declaration" to make reporting easier for HVD. 
We base this on the implementation of the INSPIRE regulation, where this principle has also been applied for several years. 
For INSPIRE you have to declare how compliant you are. For this, INSPIRE developed Technical Guidelines and Annexes that state for each theme what the degree of conformity should be. Then in the implementation in metadata a quality block is provided, in which a statement can be made against your annex and your conformity as a data provider, so a self-declaration. 
This makes it easy to enable automatic reporting. An additional advantage is that the data provider is best placed to self-declare how compliant his data is (content, conditions, key attributes). 
We could apply this self-declaration to the key attributes and other requirements (such as granularity and format, for example) that can be read in the Annexes, by topic (usually stated in the first paragraph).

![Self-Declariation](https://github.com/SEMICeu/DCAT-AP/assets/69851864/6c5b94f6-e301-43fa-8386-bb8265067c9f)

**Comment by bertvannuffelen** [comment]
@Nolfge we included in the section on [specific data requirements](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#c7) this suggestion. Nevertheless a concrete agreed form (the details of an acceptable, trustable self-declaration) are not included and work for the future.
