### ISSUE TITLE
dcat:CatalogRecord - remove dct:description?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#33]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:description:
- Usage: 0%
- Should this property be removed/withdrawn/deprecated?

**Comment by bertvannuffelen** [comment]
Hi,

here the analysis of the European Data Portal makes a false impression.
The catalogrecord is something from the catalogue itself, and which is not "copied" from any harvested source. 

So it is more an indication that the European Data Portal does not have a good idea what to enter in this property.

Bert

**Comment by makxdekkers** [comment]
Are you implying that CatalogRecord will never be harvested? If that is the case, and CatalogRecord is just a 'local' class, is the class at all necessary in the profile? The profile is primarily intended for exchange of data.
Or do you and others feel that it would be useful for harvesters to fetch this information from other portals? Do other portals actually use the class?

**Comment by bertvannuffelen** [comment]
It will be harvested if present, and it can be used to optimize the harvesting if correctly used.
But most harvesting ODPs are ignoring it as it is seldom supplied and created by the ODPs. 

Also a harvester ODP cannot just copy the catalog records into its own catalog (as the catalog record describes the modifications in the harvested catalog), it will use it. 
A harvester ODP, like the European ODP, should create itself the catalog records for its own catalog. 
And that is clearly not done. (or at least not present in the triple store.)

So the necessity is depending on what is the quality and the information (in a semantically unambiguous way) you want to share. 
In my opinion the catalog record has its value, is useful and has clear semantics, but I think that the practice is not taking benefit from it. It is hence the practice that should adapt not the profile ;-)

Independent of this discussion, I am curious on what we all understand under "The profile is primarily intended for exchange of data." 
This is a foundational discussion. And that will drive the rest of the discussions.

**Comment by makxdekkers** [comment]
@bertvannuffelen Just to bring back the focus on the issue at hand: this issue does not question the relevance of the Catralogue Record (which has a 100% occurrence in EDP -- every dataset has an associated catalogue record). The analysis showed that the property dct:description was not used.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:description from CatalogRecord.

**Comment by NatasaSofou** [comment]
It is proposed to keep it in the model for now.
