### ISSUE TITLE
[Editorial] Dataset, dcat:hasVersion and dcat:isVersionOf

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#331]
Conf. [W3C/DCAT Use of inverse properties](https://www.w3.org/TR/vocab-dcat-3/#inverse-properties), dcat:isVersionOf shouldn't be included i DCAT-AP.

**Comment by jakubklimek** [comment]
@bertvannuffelen `dcat:isVersionOf` is still mentioned as a replacement in [Deprecated properties and classes](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#deprecated-properties-and-classes) and the [notes on alignment with DCAT 3](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#notes-on-alignment-with-dcat-3).

**Comment by skornsekj** [comment]
@bertvannuffelen 
Is it possible that dcat:hasVersion and dcat:isVersionOf still exist in the corresponding shacl and should not be included there either.
