### ISSUE TITLE
[Editorial] Dataset member of a Dataset Series, dcat:next and dcat:prev

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#332]
Conf. [W3C/DCAT Use of inverse properties](https://www.w3.org/TR/vocab-dcat-3/#inverse-properties), dcat:next shouldn't be included i DCAT-AP.

**Comment by bertvannuffelen** [comment]
applied in accordance to the decision taken to adopt W3C DCAT inverse properties statement.

**Comment by skornsekj** [comment]
@bertvannuffelen 
Is it possible that dcat:next and dcat:prev still exist in the corresponding shacl and should not be included there either.
