### ISSUE TITLE
Data service - conforms to

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#333]
The usage note for the property dcat:endpointDescription in the class dcat:DataService says "... while dct:conformsTo is used to indicate ...". However, the property dct:conformsTo is not explicitly included in the class dcat:DataService.

**Comment by bertvannuffelen** [comment]
Adjusted usage note to create a better cross-reference. In addition, adjusted the definition of the property dct:conformsTo to relate to Data Service instead to a more general Catalogued Resource.

**Comment by jimjyang** [comment]
> In addition, adjusted the definition of the property dct:conformsTo to relate to Data Service instead to a more general Catalogued Resource.

In https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DataService there is no dct:conformsTo. Hope this will be added in the coming release.

**Comment by jakubklimek** [comment]
@jimjyang it is in the 3.0.0-draft: https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/#DataService.applicationprofile
