### ISSUE TITLE
[Editorial] Catalogue - language

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#335]
The definition of the property language (dct:language) in the class Catalogue (dcat:Catalog) says now "A language used in the textual metadata describing titles, descriptions, etc. of the Datasets in the Catalogue.", which is too narrow because a catalogue may contain more than just datasets. 

Change to e.g. "... of the resources (e.g. Datasets, Data services) in the Catalogue".

**Comment by PwC-Arthur** [comment]
Hi Jim

Several definitions were changed subsequent to issue #297 because of the same constraints, i.e. being too narrow, as you describe is the case for this definition. We will adjust the definition accordingly in the draft that will soon be released.
