### ISSUE TITLE
[Editorial] Catalogue - themes

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#336]
The definition of the property themes (dcat:themeTaxonomy) in the class Catalogue (dcat:Catalog) says now "A knowledge organization system used to classify the Catalogue's Datasets."

Is this property only ment for Datasets in the Catalogue, and not "catalogued resources" in general?

**Comment by PwC-Arthur** [comment]
Hi Jim

This issue was addressed by @terjesyl in issue #297 and is already resolved in the draft that will soon be released.
