### ISSUE TITLE
[Editorial] Catalogue record - application profile

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#338]
The definition of the property application profile (dct:conformsTo) in the class Catalogue record says now "An Application Profile that the Dataset's metadata conforms to." which is too narrow because a catalogue may contain metadata about other resources in addition to datasets.

**Comment by PwC-Arthur** [comment]
Hi Jim

This issue was addressed by @terjesyl in issue #297 and is already resolved in the draft that will soon be released. This is the case for both Catalogue Record and Data Service.
