### ISSUE TITLE
licenseDocument

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#34]
Hi,

In the context of the Flemish Open Data portal we would like to have advice on the creation of a specific instance of a license document. 

Q: Is there a LicenseDocument vocabulary which allows to describe a license document by extending an existing license with instances of clauses?

The example case is as follows: the Flemish government has defined 2 licenses which state in short: you can use the data if you 
    a) mention the source, or
    b) pay a fee 

Now we would like to create a license document that instantiates the general license document with the specific name of the source (or the fee).  

Pointers to how we best address this topic are welcome. 

Bert

**Comment by giorgialodi** [comment]
Hi Bert, 
in Italy we created a license vocabulary (reusing part of the controlled vocabulary mentioned in the current DCAT-AP specifications). The licenses we included are those currently used in the Italian open data catalogues we harvest. 
You can find the vocabulary here: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/Licenze (there are labels in ITA, ENG, DEU, FRA).

**Comment by makxdekkers** [comment]
@bertvannuffelen The same issue was brought up on [Joinup](https://joinup.ec.europa.eu/discussion/attribution-clauses) a year ago. 
The ODI's Open Data Rights Statement Vocabulary has two properties, [attributionText](http://schema.theodi.org/odrs/#prop_attributionText) and [attributionURL](url).

**Comment by bertvannuffelen** [comment]
@giorgialodi, thanks for the pointer. 
@makxdekkers: this is an interesting reference. I found in https://creativecommons.org/ns a vocabulary however the cc:attributionName is associated with work and not with the license as a clause.
I have a look to the ODRS to see if this matches better our intentions.

kr
Bert

**Comment by DGatt** [comment]
Germany did just the same as Italy (http://www.dcat-ap.de/def/licenses/). Maybe an indicator that such a thing could be useful on the European level.
The German application profile also introduced licenseAttributionByText as a property of the distribution. Personally, I feel that something like a Rights Statement (ODRS) - as a resource that describes the relationship between a Dataset and its Licence(s), and is also used to describe additional contextual information that applies to the re-use of a dataset -  is the way forward.

**Comment by makxdekkers** [comment]
There is also an Licence NAL at the Publications Office: http://publications.europa.eu/mdr/authority/licence/.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by NatasaSofou** [comment]
No change. Note discussion at DXWG, see: https://github.com/w3c/dxwg/issues/114
