### ISSUE TITLE
Dataset: usage note

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#340]
What does the usage note for the class [Dataset in 3.0.0-draft](https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/#Dataset) mean? "If a Dataset is used as part of a Dataset Series, the properties listed below can be used additionally, or slightly differently to those listed for the Dataset outside of a Dataset Series."

e.g. "... used additionally", in addition to what?

**Comment by bertvannuffelen** [comment]
This is a editorial relict from the previous version. To be removed.
