### ISSUE TITLE
Dataset: several properties missing

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#341]
Several properties that are in [DCAT3](https://www.w3.org/TR/vocab-dcat-3/#Class:Resource) are missing in the class [Dataset in 3.0.0-draft](https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/#Dataset): 
* previous, dcat:prev
* replaces, dcterms:replaces
* has part, dcterms:hasPart

**Comment by bertvannuffelen** [comment]
This is in line with https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/#specoverview and https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/#inverse-properties.

If we add an inverse property then only the one that is mandated by DCAT is included; the inverse is not included. This to stress that only the minimal effort from publishers is expected. They still can add the others, but then the reciever does not has to do an interpretation effort. 

For your info, _replaces_ and _has part_ were not part of DCAT-AP 2.1.1 for Datasets.

**Comment by jimjyang** [comment]
I didn't mean to add inverse properties, but the primary ones. 

Nevertheless, I understand now that this is actually a "reuse as-is"-issue, conf. the discussion related to #339.

**Comment by jimjyang** [comment]
No actions needed, I close this issue.
