### ISSUE TITLE
Support for data integration

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/DCAT-AP#35]
By Bert van Nuffelen, created from comment at https://github.com/SEMICeu/DCAT-AP/issues/4:

I in general like the number of fields as they have mostly some good definitions and are there to support some usecases.

They are rightly mostly annotated as optional, as the effort to give good values to them (and maintain it) requires effort.
The statistics shown by each of the issues are for me indications of two problems:
a) the definition did not fitted well, and hence not used
b) the data could not be collected (for what ever reason)

Removing the properties to those that most portals are providing has potential impact on the usability of the catalogue.
I think we should consider what are the target audiences for the catalogue and the see if the data provided is aiding to achieve that purpose. Today's open data portals mostly are oriented to accidental visitors who want to know what data exists and a bit browse through it. The catalogues are seldom used as a navigator to the technical audiences which would use the catalogues as their source to combine the actual data.
In order to do so technical properties as checksums, formats, sizes, api descriptions are needed.
And maybe this is a discussion worth: how can DCAT-AP handle more consistently the different dissemination forms and provide a highlevel description for it so that this data integration can be realized.
It would be great if we could come to an extension approach so that this can also lead to good interoperability. I am aware that this has it limits from the perspective of DCAT-AP, but if taking the perspective of the developers, self-descriptive services/distributions are what they ask for. In my opinion, it would be fantastic if it would be clarified how this bridge is made.

**Comment by makxdekkers** [comment]
Bert, the issue of how DCAT can better support data integration is also discussed in the DXWG group at W3C. See for example https://www.w3.org/TR/dcat-ucr/#ID7 and https://www.w3.org/TR/dcat-ucr/#ID26. It seems to me that if DXWG finds a solution for it, the DCAT-AP group could consider adopting that approach.

**Comment by makxdekkers** [comment]
Proposed resolution | Retain issue for next major semantic release, also taking   into account the discussions at W3C DXWG, see https://www.w3.org/TR/dcat-ucr/#ID7   and https://www.w3.org/TR/dcat-ucr/#ID26

**Comment by addragan** [comment]
Proposed resolution: Resolution to be proposed in line with DCAT review that is currently under development (https://www.w3.org/TR/vocab-dcat-2/#qualified-relationship, https://www.w3.org/TR/vocab-dcat-2/#qualified-attribution).

**Comment by bertvannuffelen** [comment]
On the one hand this issue is resolved with the introduction of new properties and classes, and further restrictions. But on the other hand it refers to a more in depth discussion, which can take place in the future.
