### ISSUE TITLE
HVD: Annex vs Application Profile?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#351]
Referring to the definitions of **Application Profile** and **Annex to an Application Profile** in [5. Terminology](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#specterminology), why is DCAT-AP HVD called an "Annex" in chap. [15. High Value Datasets in DCAT-AP](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#high-value-datasets), when DCAT-AP HVD actually adds more specificity to DCAT-AP?  

Examples of more specificity: 
* properties that are mandatory in DCAT-AP HVD but non-mandatory in DCAT-AP: [applicable legislation](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#DataService.applicablelegislation), [contact point](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#DataService.contactpoint) etc. in the class Data Service
* properties that are explicitly specified in DCAT-AP HVD but not in DCAT-AP: [documentation](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#DataService.documentation), [HVD category](https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#DataService.HVDcategory) etc. in the class Data Service.

**Comment by bertvannuffelen** [comment]
We called it annex because we saw it as part of DCAT-AP but focussed on HVD datasets. 
It is indeed profiling the use of DCAT-AP for HVD. 

With the word _annex_ we wanted to stress the strong connection rather than turning it in a separate work with a separate workinggroup.
