### ISSUE TITLE
Data Service - documentation (foaf:page)

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#352]
Any reason why the property "documentation (foaf:page)" is not explicitly included in the class Data Service?

Conf. [the minutes from the webinar 2023-11-07](https://joinup.ec.europa.eu/sites/default/files/event/attachment/2023-12/20231107%20Webinar%20dedicated%20to%20the%20status%20and%20governance%20of%20DCAT-AP%20%281%29.pdf) about issue #310 (although the minutes said "... mapped to foaf:agent" instead of "... mapped to foaf:page").

**Comment by bertvannuffelen** [comment]
@jimjyang 
This property has been added in https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService for capturing the requested information about the quality of service. (See https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#DataService.documentation)

However it was indeed agreed to lift this also to DCAT-AP and that was not executed. This has now been addressed.
