### ISSUE TITLE
Cardinality and usage note of `dct:type` in `dcat:Dataset`

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#360]
`dcat:Dataset`'s property `dct:type` had a cardinality of `0..*` in DCAT-AP 2.1, we discussed it here: https://github.com/SEMICeu/DCAT-AP/issues/153#issuecomment-976399205

In [DCAT-AP 3.0](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.type) it is back to `0..1`.  I guess it's a mistake?

Also the usage note says:
> A recommended controlled vocabulary data-type is foreseen. 

But we have now a recommended vocabulary: 
![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/af6e309b-0695-47e9-8fdc-49d333e411dc)

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de This is indeed an unspotted mistake. Probably a mixup with the usage of dct:type of Agent.

The connection with the codelist (and it status) is an interesting remark, as this is one of the open alignments to be made.
But for now, a max-cardinality * or n means that one can have multiple values for that property. 
It does not state it are values from a single or multiple codelists. 

That latter interpretation the usage of a single codelist is for the Codelist section to be expressed.
