### ISSUE TITLE
SHACL: prev, next, fist, last, isVersionOf are still included in 3.0 SHACL?

### ISSUE THREAD

**Issue by skornsekj** [SEMICeu/DCAT-AP#361]
@bertvannuffelen 
Is it possible that dcat:next, dcat:prev, dcat:first, dcat:last and isVersionOf, are still included in the provided 3.0 SHACL and should not be included there?

**Comment by bertvannuffelen** [comment]
@skornsekj they already have been removed in the draft release of DCAT-AP 3.0.0 that we are using to finalise the official release.

Just to confirm the usage of these in DCAT-AP: these properties can be used, but they have no additional restrictions than the one DCAT prescribes.

**Comment by skornsekj** [comment]
@bertvannuffelen 

I'm not sure, I understand. These properties are not described in de Respec document and I cannot find them in https://semiceu.github.io/DCAT-AP/releases/3.0.0/#quick-reference. For me is not clear if these properties are part of DCAT-AP 3.0.  So, MUST a Receiver accept these properties when the Receiver want to be to conform DCAT-AP. My current interpretation is, these properties are no part of DCAT-AP. Is that correct? 

Can you give an indication when we can expect the finale SHACLs? 

Thanks!

**Comment by bertvannuffelen** [comment]
@skornsekj  on the draft version (https://semiceu.github.io/DCAT-AP/releases/3.0.0-draft/) the shacl shapes are now updated. They should be now be ready for release.
