### ISSUE TITLE
Mapping to the License NAL in the context of HVD

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#367]
In the scope of implementing HVD support to the Czech catalog, also related to #253, I ran into a question of how the mapping to the [EU License NAL](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/licence) should actually look like. I want to use SKOS, and I followed the [examples in DCAT-AP HVD](https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/#expressing-legal-conditions), but still, the exact expected usage is a bit unclear, and it basically boils down to the question of how the CC licences are hierarchically ordered using SKOS?

Is CC0 broader or narrower than CC BY 4.0? The EU NAL does not contain this hierarchy.

The DCAT-AP HVD examples now presume that I can use `skos:exactMatch` from a local license definition to the EU NAL. However, if I could do that, I could as well use the EU NAL directly. The problem is that I cannot do that. I can either use `skos:closeMatch` to a certain degree, based on effects on the reuser, or `skos:broadMatch` or `skos:narrowMatch` - but here I am not sure of the expected direction.

To give a specific example, one of the options in Czechia is to say that a distribution is not affected by any intellectual property rights. The effect on the reuser is the same as the distribution being licensed by CC0. But CC0 presumes that there is something to license. Which is not the case here. Therefore, I could say that this case is even more permissive than CC0 (and here I am not sure of the direction), or that it is a close match (similar effects, but not exactly the same).

Answer to this question may also affect the upcoming HVD reporting, as the license should be at least as permissive as CC BY 4.0 and the fulfillment of this requirement will, I presume, have be part of the report, and therefore based on the mapping. And, if I say that a distribution is `skos:closeMatch <cc-by-4.0>`, it is unclear whether it fulfills the criterion or not. That is why I would rather use `skos:broadMatch` or `skos:narrowMatch`, which makes it clear.

**Comment by bertvannuffelen** [comment]
I propose to follow in accordance to the hierarchy relationship of SKOS in which the most generic concept (the concept higher in the hierarchy, i.e. closer to the top-concept) is more general than the leaf concept, to have the most permissive licences at the top and the most restrictive at the bottom.  

From https://www.w3.org/TR/skos-reference/#semantic-relations

>
> A triple <A> skos:broader <B> asserts that <B>, the object of the triple, is a broader concept than <A>, the subject of the triple. 
> Similarly, a triple <C> skos:narrower <D> asserts that <D>, the object of the triple, is a narrower concept than <C>, the subject of the triple.
>

and https://www.w3.org/TR/skos-reference/#mapping

> 
> skos:broadMatch is a sub-property of skos:broader, skos:narrowMatch is a sub-property of skos:narrower, and skos:relatedMatch is a sub-property of skos:related.
> 

It would follow that  a local licence L1 which is more permissive as CC-BY-4.0 would be encoded as follows:
```
<L1> skos:narrowMatch <CC-BY-4.0>.
<CC-BY-4.0> skos:broadMatch <L1>.
```

**Comment by jakubklimek** [comment]
I agree.

Therefore, to make it explicit, for the purpose of HVD reporting, the following license mappings should be OK:
```turtle
#These are acceptable
<L1> skos:narrowMatch <CC-BY-4.0>.
<L2> skos:narrowMatch <CC0>.
<L3> skos:exactMatch <CC-BY-4.0>.
<L4> skos:exactMatch <CC0>.
```

Furthermore, when considering:
```turtle
<L5> skos:closeMatch <CC0>.
```
one should instead make it explicit that
```turtle
<L5> skos:narrowMatch <CC-BY-4.0>.
```

And 
```turtle
<L6> skos:closeMatch <CC-BY-4.0>.
```
is not OK, because it is unclear whether the closeness is rahter narrower or rather broader.

If considering just the purpose of HVD reporting, we could also do without `CC0` altogether, as the only cut-off for HVD is `CC-BY-4.0`. That would make the mapping simpler. However, I think we should take this opportunity that previously unmapped licenses will now be mapped, and distinguish the `CC0` and `CC-BY-4.0` cases. What do you think @bertvannuffelen ?

**Comment by bertvannuffelen** [comment]
Addressed in https://semiceu.github.io/DCAT-AP/releases/3.0.0-hvd/#assessment-support-for-licences.
