### ISSUE TITLE
Dataset/Distribution: cardinality of dcat:spatialResolutionInMeters and dcat:temporalResolution

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#372]
![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/ee88fc2f-b782-464d-b6d3-469a23a37131)

dcat:spatialResolutionInMeters and dcat:temporalResolution in Dataset and Distribution have the cardinality `0..*`. In https://github.com/SEMICeu/DCAT-AP/issues/114 we documented that we want them to have `0..1`. In 2.1.1 they had `0..1`:

![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/0b8ea55e-8739-49eb-b7db-3a5ca9eb46f2)

I assume it's an errata ticket?

- https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.spatialresolution
- https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.spatialresolution
- https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.temporalresolution
- https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.temporalresolution

**Comment by bertvannuffelen** [comment]
This is a bug in the transition from version 2.1.1 to the new HTML representation. Nevertheless it might be opened as an issue when aligning with GeoDCAT-AP.
