### ISSUE TITLE
DatasetSeries --> Description: Optional but (1..*)

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#373]
The class description gives `1..*` as the cardinality for `dcterms:description`: 

![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/eadc2c9e-1771-4ce1-8912-ac44a3545f11)

https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DatasetSeries.description

The [Quick Reference](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#quick-reference) says it is optional:

![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/ad2f8466-6439-4d55-bece-64ef58a465e7)

My guess is a copy/paste error from `dcat:Dataset`. Hard to spot, if the "Property Type" is not shown in the main description.

**Comment by PwC-Arthur** [comment]
The usage scope of the property was changed to be mandatory instead of optional in the draft.

Thanks for pointing this out.
