### ISSUE TITLE
Incomplete list of 'used classes' in 10.2 "Controlled vocabularies to be used"

### ISSUE THREAD

**Issue by skornsekj** [SEMICeu/DCAT-AP#374]
Seems that following classes in 'Used for Class' are missing in 10.2 "Controlled vocabularies to be used"

- dct:publisher - missing class: 'Data Service'
- dcat:theme - missing classes: 'Data Service'; 'Catalogue'

**Comment by PwC-Arthur** [comment]
Hi, for both properties the missing classes were added. Thanks for pointing this out.
