### ISSUE TITLE
Differences dcat-ap-SHACL.ttl and Respec document

### ISSUE THREAD

**Issue by skornsekj** [SEMICeu/DCAT-AP#379]
@bertvannuffelen 
There seems to be some differences between the new draft SHACL https://github.com/SEMICeu/DCAT-AP/blob/gh-pages/releases/3.0.0-draft/shacl/dcat-ap-SHACL.ttl and the Respec document. 

We found the following properties missing in the draft SHACL. 
- Dataset: keyword
- Dataset: version notes
- Distribution + CatalogRecord: description
- Distribution + CatalogRecord:: title

**Comment by bertvannuffelen** [comment]
@skornsekj thanks for the feedback. We had a parameter wrongly configured in our tooling which resulted for low constrainted properties (e.g. optional and range Literal) to not be taken into account. In the next update these will be included in the SHACL. But as said, it may be only a nodeKind statement for that property.
