### ISSUE TITLE
DCAT: Distribution – Suggestion attribute for record - ‘temporal granularity’

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#38]
def: the temporal granularity is the temporal resolution of the contained data 

Datatype: rdf:Literal String Enum aus: second, minute, hour, day, week, month, quarter, year, 5-years

Reasoning for change:  
This  #metadata was already present in the former CKAN / OGD schema; is partially needed e.g. by the statistical domain or for metadata attribution of fiscal data. Notice: It is not the same as temporal coverage.

**Comment by akuckartz** [comment]
Same :-1: comment as in #39 regarding range rdfs:Literal

**Comment by makxdekkers** [comment]
@init-OGD There is actually a property `[dcat:granularity](https://www.w3.org/ns/dcat#granularity)` in the DCAT namespace, but this was deprecated during the development of DCAT. I am not sure if we could request un-deprecating the property. Do you know of a property defined elsewhere that could serve this purpose?
As to the range, it would be better to make this skos:Concept. There is a actually a controlled vocabulary at the Publications Office that includes almost all of the values that you list (with the exception of anything over a year): the MDR Time Period NAL http://publications.europa.eu/mdr/authority/timeperiod/.

**Comment by makxdekkers** [comment]
Proposed resolution | Retain issue for next major semantic release.

**Comment by addragan** [comment]
Proposed resolution: Align DCAT-AP with DCAT that is also currently developing this area, see discussion https://www.w3.org/TR/vocab-dcat-2/#temporal-properties.

**Comment by init-dcat-ap-de** [comment]
In DCAT-AP.de 1.0.2 we now use dcat:granularity with the publications office MDR time period http://publications.europa.eu/mdr/authority/timeperiod/.

**Comment by bertvannuffelen** [comment]
resolution: alignment with DCAT 2.0 has happened.
