### ISSUE TITLE
Clarification required.

### ISSUE THREAD

**Issue by jucajuca** [SEMICeu/DCAT-AP#387]
Hello,

We struggle to find a clear and concise definition of what defines a High Value **Dataset** in the specification. In our view, a dataset becomes HVD if it has any "children" labelled as HVD (upwards inheritance). 

Can you answer the following questions with **Yes** or **No**? We need absolute clarity about this topic.

Is a dataset automatically a HVD if it contains at least a valid High Value Distribution?

Is a dataset automatically a HVD if it contains at least a valid High Value Data Series?

**Comment by bertvannuffelen** [comment]
@jucajuca DCAT-AP HVD does not provide any inferenced interpretation of what is a High Value Dataset.
It only records High Value Datasets. 

High Value Datasets are datasets that are tagged/labelled with  the appropriate value for the property dcatap:applicableLegislation. 
It is thus the owner/publisher of the dataset that in coordination with it national High Value Dataset responsible decides this is an High Value Dataset.

Any attempt to interprete of a dataset (e.g. the business register of Finland) as a High Value Dataset is a legal interpretation that can be challenged at the responsible MS. In the example Finland. DCAT-AP HVD only _records_ the decision of Finland. If they decide that the dataset is not subject to the HVD IR, then it is their choice. The impact might be an infringement of HVD IR but that is again outside DCAT-AP HVD.

**Comment by jucajuca** [comment]
Thanks for the clarification.
