### ISSUE TITLE
[HVD] Dataset.distribution: The cardinality should be 0..*

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/DCAT-AP#396]
[This was already raised in #376 when it was v.2.2. I couldn't see that this is solved now in v.3.0.0-hvd, so I raise it again]

The cardinality for the property [Dataset.distribution (`dcat:distribution`)](https://semiceu.github.io/DCAT-AP/releases/3.0.0-hvd/#Dataset.datasetdistribution)  (`dcat:distribution`) is `1..*`, while in the Annex A this property is catetorized as `Recommended` (thus `0..`). So, it is at least inconsistency between the specification of the property and the quick reference in Annex A. 

Furthermore, since [Bulk Download in HVDR is mapped onto dcat:Distribution](https://semiceu.github.io/DCAT-AP/releases/3.0.0-hvd/#c-terminology), and HVDR does not always require Bulk Download (e.g. "for historical versions of datasets: APIs or bulk download", conf. the last bullet point under 2.2.a in the HVDR Annex), the cardinality for this property should not be `1..`. 

[Yes, it is of course possible to relate to a `dcat:DataService` indirectly via a `dcat:Distribution` in order to be compliant with the cardinality requirement `1..*`, but no, this is not the way that [10.8](https://semiceu.github.io/DCAT-AP/releases/3.0.0-hvd/#apis-are-mandatory) recommends]

**Comment by bertvannuffelen** [comment]
Included in the next release a solution, in which the formal representation is relaxed, but the usagenotes and validation is strict.
