### ISSUE TITLE
DCAT: Distribution – suggestion attribute for record – ‘planned availability’

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#40]
Def: 
Uses a list of guaranteed availabilities, like 

http://dcat-ap.de/def/plannedAvailability/temporary
http://dcat-ap.de/def/plannedAvailability/experimental
http://dcat-ap.de/def/plannedAvailability/available
http://dcat-ap.de/def/plannedAvailability/stable

Datatype: rdfs:resource 

Reasoning for change:
This concept was added to dcat-ap.de and seems to be a good extension for dcat-ap itself; perhaps even W3C dcat. 
The concept of indicating a datasets planned lifetime close to other metadata of the dataset seems a good idea for fostering reuse and decoupling the dataset metadata from its technical publishing channel.

**Comment by akuckartz** [comment]
`rdfs:Resource`' is better that `rdfs:Literal` but I think this can and should be restricted to `skos:Concept`.

**Comment by makxdekkers** [comment]
This seems to be essentially an aspect of 'status'. If so, maybe the controlled vocabulary [MDR Dataset status](http://publications.europa.eu/mdr/resource/authority/dataset-status/) could be used and maybe extended if necessary?

**Comment by DGatt** [comment]
The idea is actually from the silver level of the ODI open data certificates (https://certificates.theodi.org/en/about/whatyouneed ). It describes an aspect of the "level of dependability" of the data: "For a silver certificate, you should intend for the data to be available in the same form for at least a year. If it is not going to be available for at least a year, it is unlikely any reuser will invest time to use it except in proofs of concept."
As such the concept seems to be orthogonal to "status". I agree that it could be restricted to skos:Concept.

**Comment by makxdekkers** [comment]
A couple of questions related to this:
1. what charateristic of the dataset does this list of terms describe? The terms do not seem to be for "planned lifetime"; for "lifetime", I would expect a value of type "period of time". Would it be more like "availability"?
2. would this be similar to `schema:availability`? see http://schema.org/availability. Or do you know of other standards that have a property that could be reused?
3. what is the exact meaning of each of the proposed values in the vocabulary? It looks like the value `:available` is in a different dimension than the other three.

**Comment by DGatt** [comment]
At https://certificates.theodi.org/ one can find the following elaborations:-  

- temprorary: it might disappear at any time
- experimental: it's available experimentally but should be around for another year or so
- available: it's in your medium-term plans so should be around for a couple of years
- stable: it's part of your day-to-day operations so will stay published for a long time
- 

 
This doesn't amount to an exact definition, but I think it describes very well the reality, where a precise lifetime of the data is seldom on the records, yet one can give the users at list a hint how much they can rely on the future availability. A value type "period of type" is nevertheless an alternative.

**Comment by makxdekkers** [comment]
Proposed resolution | Retain issue for next major semantic release.

**Comment by addragan** [comment]
Proposed resolution: Align DCAT-AP with DCAT that is also currently developing this area, see discussion https://www.w3.org/TR/vocab-dcat-2/#Class:Period_of_Time.

**Comment by init-dcat-ap-de** [comment]
We do not see that "Period_of_time" will cover the requirement of "indicating whether something is meant to be persistent or just provided for temporal usage." 

In both cases indicating an exact time will not tell the user about the intended stability of an URL.

**Comment by init-dcat-ap-de** [comment]
We suggest to name the element "availability" with the options
temporal
experimental
available
stable

and make it a recommended one.

**Comment by init-dcat-ap-de** [comment]
In the UML diagram dcatap:availability is marked as optional, in the PDF as recommended.

**Comment by init-dcat-ap-de** [comment]
The property now has the range skos:Concept, in dcat-ap.de we use rdf:ressource and a controlled vocabulary with URIs. We recommend something similiar for dcat-ap.

**Comment by bertvannuffelen** [comment]
resolution: controlled vocabulary added to the RDF distribution of DCAT-AP.

**Comment by andrea-perego** [comment]
Sorry, @bertvannuffelen , could you please explain which controlled vocabulary has been added? From the discussion it is not clear to me.

**Comment by bertvannuffelen** [comment]
@andrea-perego see at the bottom of the RDF distribution: https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.0.0/Draft/dcat-ap_2.0.0.rdf

**Comment by andrea-perego** [comment]
Thanks, @bertvannuffelen .

A couple of comments:
- The URI of the concept scheme includes a version number, which is not a best practice as it may raise interoperability issues. I would suggest removing the version number, and deal with versioning by using appropriate properties specifying whether a concept has been deprecated, replaced by another one, etc. It would also be important to specify the status of a concept - see https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/concept-status
- I would recommend against including code lists, thesauri, etc. in the DCAT-AP RDF definition. They'd rather be moved in separate files, and made dereferenceable.

Overall, I think it is important having a consistent policy for controlled vocabularies developed in the framework of DCAT-AP. In the past, this was addressed by proposing the creation of a named authority table to be maintained by the OP - personally, I think this is still the best option.

**Comment by matthiaspalmer** [comment]
I agree with @andrea-perego , the concepts should be dereferencable and available separately in a separate file. 

I am implementing support for DCAT-AP2 now and could not first find the concepts as they are not linked to from the current specification. It was only by looking at the change log I found this issue and realized that the concepts where described in the RDF file.

**Comment by bertvannuffelen** [comment]
@andrea-perego , @matthiaspalmer  we will initiate this discussion with the Publication Office for the future management of this codelist.
