### ISSUE TITLE
DCAT: Distribution - Suggestion attribute for record – ‘LicenseattributionByText’

### ISSUE THREAD

**Issue by init-OGD** [SEMICeu/DCAT-AP#41]
Def:
An auxiliary to save mandatory attribution license texts.    

Datatyp: rdfs:Literal

Reasoning for change:
attribution licenses require an information of how to quote correctly the attribution. This information was added to the dcatde: namespace -> this property should be added to the W3C DCAT.

**Comment by akuckartz** [comment]
Same :-1: comment as in #39 regarding range rdfs:Literal

**Comment by makxdekkers** [comment]
@init-OGD This is indeed information that would be useful to provide with attribution-type licences. In this case, I don't see a problem with a range of rdfs:Literal. 
As you note, it is an issue that could be considered by W3C in the process of revising DCAT. You are very welcome to make this comment by sending a message to public-dxwg-comments@w3.org, or by creating an issues at https://github.com/w3c/dxwg.

**Comment by DGatt** [comment]
Another way of resolving the issue it to define a few properties of the RightsStatement on the distribution level (with the help of ODRS)

[](http://schema.theodi.org/odrs#attributionText)
[](http://schema.theodi.org/odrs#attributionURL)
[](http://schema.theodi.org/odrs#copyrightNotice)
[](http://schema.theodi.org/odrs#copyrightStatement)
[](http://schema.theodi.org/odrs#databaseRightHolder)
[](http://schema.theodi.org/odrs#copyrightYear)

**Comment by makxdekkers** [comment]
@DGatt When you write "_define a few properties of the RightsStatement on the distribution level_", do you mean that those properties would be defined as properties of the Distribution? E.g. a triple like:

`<Distribution-001> <odrs:attributionText> "Some text"`

This is not the way ODRS envisages this. ODRS makes `odrs:attributionText` a property of `odrs:RightsStatement`, which is, according to the [RDF schema](https://github.com/theodi/open-data-licensing/blob/master/schema/schema.ttl), a sub-class of `dct:RightsStatement`. 

So, it looks like the solution can be applied without changes to the specification. After all, `dct:rights` is specified in DCAT-AP as an optional property for `dcat:Distribution`, so it can already be used to link to an `odrs:RightsStatement`.

**Comment by makxdekkers** [comment]
Proposed resolution | No change to the specification.

**Comment by addragan** [comment]
The issue will be closed and no changes will be done to the specification.
