### ISSUE TITLE
DCAT: Dataset - Suggestion attribute for record – ‘dct:contributor’

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#42]
Def:
Dataset contributor as a person or an organisation who, in addition to the creator, has given a relevant input to the dataset.

Datatype: rfds:Literal

Reasoning for change:
As in Germany we need additional roles, we reintroduced the existing Dublin core property “contributor”.

**Comment by akuckartz** [comment]
Same :-1: comment as in #39 regarding range rdfs:Literal

**Comment by makxdekkers** [comment]
The Dublin Core property `dct:contributor` would be the obvious candidate. The range of that property is `dct:Agent`, not `rdfs:Literal`.

**Comment by makxdekkers** [comment]
Proposed resolution | Retain issue for next major semantic release.

**Comment by addragan** [comment]
Proposed resolution: Align DCAT-AP with DCAT that is also currently developing this area, see discussion https://www.w3.org/TR/vocab-dcat-2/#qualified-forms.

**Comment by bertvannuffelen** [comment]
resolution: DCAT-AP has been aligned with this.
