### ISSUE TITLE
innerMimeType - There might be a need of having an inner mime type (for ZIP-Containers).

### ISSUE THREAD

**Issue by init-OGD** [SEMICeu/DCAT-AP#43]

**Comment by akuckartz** [comment]
innerMimeType is mentioned on page 4 in https://joinup.ec.europa.eu/sites/default/files/event/attachment/2017-12/20171208%20DCAT-AP%20webinar%20minutes_v0.03.pdf

I would prefer "MediaType" to "MimeType".

**Comment by makxdekkers** [comment]
There is a guideline "[How to refer to media types within ZIP files?](https://joinup.ec.europa.eu/release/how-refer-media-types-within-zip-files)".

**Comment by makxdekkers** [comment]
Proposed resolution | No change.
