### ISSUE TITLE
SPDX Vokabular - the existing SPDX vocabulary features only ONE has algorithm. This is definitely not enough and does not even covers those algorithms used by CKAN today.

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#44]

**Comment by makxdekkers** [comment]
@init-OGD Are you suggesting to add a new property to the Distribution? If so, do you know of any existing properties in other vocabularies that could be used?

**Comment by makxdekkers** [comment]
Proposed resolution | Retain issue for next major semantic release.

**Comment by addragan** [comment]
@init-dcat-ap-de Request for more details on the issue. Is it a suggestion to add a new property to the Distribution? If so, do you know of any existing properties in other vocabularies that could be used?

**Comment by init-dcat-ap-de** [comment]
We wanted to have a greater choice when refering to hash algorithms using SPDX Vocabulary

Meanwhile  today, SPDX 2.1 features 3 algorithms

https://spdx.org/rdf/terms/
algorithm value checksumAlgorithm_md5 or algorithm value checksumAlgorithm_sha1 or algorithm value checksumAlgorithm_sha256

DCAT-AP.de knows some more (MD2; MD1; SHA384), unsure about its usage:
https://www.dcat-ap.de/def/hashAlgorithms/

**Comment by NatasaSofou** [comment]
Proposed resolution: no change
