### ISSUE TITLE
DCAT: Distribution - Correction of adms:changetype

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#45]
Reason:
adms:changeType does not exist in ADMS vocabulary therefore cannot create a verifiable controlled vocabulary constraint.

**Comment by makxdekkers** [comment]
We're looking into this.

**Comment by addragan** [comment]
The issue can be closed as it was related to issue https://github.com/SEMICeu/dcat-ap_shacl/issues/5 that was also closed.

**Comment by jakubklimek** [comment]
@addragan I vote to reopen the issue, as the issue is not resolved. The non existent vocabulary is still referenced from DCAT-AP v1.2, creating confusion. I suggest either removing it from DCAT-AP, creating a different vocabulary for it, or somehow add the vocabulary to ADMS.

**Comment by addragan** [comment]
The issue was re-opened as the non existent vocabulary is still referenced from DCAT-AP v1.2, creating confusion. Proposal to either removing it from DCAT-AP, creating a different vocabulary for it, or adding the vocabulary to ADMS. Please vote your preferred option.

**Comment by NatasaSofou** [comment]
Proposed resolution: the non-existent vocabulary will be removed from DCAT-AP 2.0.
The issue will be closed. It can be reopened in case of proposals for creating a different vocabulary for it or adding the vocabulary to ADMS.

**Comment by NatasaSofou** [comment]
#86
