### ISSUE TITLE
Proposal to use sh:targetClass in the SHACL shapes

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/DCAT-AP#46]
In a project for the French ministry of Health I am reusing DCAT-AP SHACL shapes.

The current SHACL shapes (at least those mandatory) have shapes which affect exactly the classes indicated. By using sh:targetClass, the shapes can affect subclasses (declared with rdfs:subClassOf in the model) and therefore improving the reusability of the shacl shapes.

The alternative would be define the subclasses directly in the shapes but this is not good for modularity.

**Comment by addragan** [comment]
Proposal to evaluate this issue together with #48 in the next major release cycle.

**Comment by addragan** [comment]
Proposed resolution: Use sh:targetClass in the mandatory SHACL shapes.

**Comment by EmidioStani** [comment]
Why only in mandatory shapes?

**Comment by bertvannuffelen** [comment]
applied to all shapes.
