### ISSUE TITLE
Comments on version 1.2

### ISSUE THREAD

**Issue by makxdekkers** [SEMICeu/DCAT-AP#47]
1. Section 9 needs to be updated.
2. Annex II needs to be updated. The MDR Data Theme NAL was published in 2016.
3. The change log also includes the changes from version 1.0 to 1.1 which looks unnecessary.
4. The description of the latest update in the change log states that the "_property can be repeated for multiple licences_" which is incorrect. It should say something like "_can be repeated in the case that multiple licence types apply to a licence document_".

**Comment by addragan** [comment]
Thank you for the comment, we've made the changes for #1, #2 and #4. Only the changelog remained in the more complete version, still containing the history from version 1.0 to 1.1.
