### ISSUE TITLE
dcat:Catalog - remove dct:rights?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#5]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:rights
•	Usage: 0%
•	Should this property be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
If there is no strong support for removing this property from the profile, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:rights from Catalog.

**Comment by NatasaSofou** [comment]
It was decided to keep dct:rights in the model for now.

**Comment by akuckartz** [comment]
Why?

**Comment by NatasaSofou** [comment]
The issue was tagged as "wont-fix"  and proposed to be closed with no changes in the specification. WG members were encouraged to review the issue. Since no comments or arguments were received, the issue is closed.
