### ISSUE TITLE
Problem to open the file with Protégé

### ISSUE THREAD

**Issue by delahousse** [SEMICeu/DCAT-AP#52]
Hello,
I have a problem with opening the file into Protégé, for dcat-ap 1.1. Ontology description appears, but classes and properties seems not to be loaded. Did any one had an issue related to this ?
Regards
Jean

**Comment by bertvannuffelen** [comment]
Hi Jean,

I think this is the consequence of that it is an RDF vocabulary and not an OWL ontology. The classes and properties are not declared as e.g. owl:ObjectProperty.
The reuse of owl:Ontology might be misleading here. As it is from the OWL perspective a rather empty thing. But since there is no alternative URI denoting vocabulary, one uses owl:Ontology.

The OWL reading of the file is much stricter than the RDF reading. One can however not machine readable wise detect the intended reading of the file. 
This is an recurring topic I see popping up in the semantic web community. As long we are not making our intentions explicit we end up in cases as you showed here. 


kr,

Bert

**Comment by delahousse** [comment]
Hello,
Latest version of the ontology I worked on was version 1.07 (attached). It opens ok with Protégé. Do you want me to search why further changes created a problem ? [search](url
[dcat-ap-op-ontology 7.zip](https://github.com/SEMICeu/DCAT-AP/files/3098858/dcat-ap-op-ontology.7.zip)
)

**Comment by bertvannuffelen** [comment]
Hi Jean,

I think we are talking here on different things. I was referring to the RDF file here in the releases. A file, which as expected, does not show up in protégé with classes and properties. 
You refer to a file, which I do not find here, but which is an Publication Office specific model which is not maintained in this repository. 

In that the properties have been elevated to the OWL level, so they show up.

In your file  is the following property explicit elevated
```   <!-- http://www.w3.org/ns/adms#sample -->

    <owl:ObjectProperty rdf:about="http://www.w3.org/ns/adms#sample">
        <rdfs:range rdf:resource="http://www.w3.org/ns/dcat#Distribution"/>
    </owl:ObjectProperty>
```
DCAT-AP does not do that

```
<!--  Dataset - sample   -->
 <rdf:Description rdf:about="http://www.w3.org/ns/adms#sample"> 
  <vann:usageNote xml:lang="en">Optional property. This property refers to a sample distribution of the dataset.</vann:usageNote>
  <dct:identifier>adms:sample</dct:identifier>
  <rdfs:label xml:lang="en">Dataset - sample</rdfs:label>
  <rdfs:isDefinedBy rdf:resource="https://www.w3.org/TR/vocab-adms/#adms-sample" />
  <rdfs:comment xml:lang="en">This property refers to a sample distribution of the dataset.</rdfs:comment>
 </rdf:Description>
```

however if you investigate further ADMS indeed declares it as an OWL property. So the first is a redundant statement, if the imports are done.

however also
```
<!-- http://purl.org/dc/terms/description -->

    <owl:DatatypeProperty rdf:about="http://purl.org/dc/terms/description">
        <rdfs:label xml:lang="en">description</rdfs:label>
    </owl:DatatypeProperty>
``` 
is elevated. And so far I am aware this is not defined as such, see
` curl -L -H "Accept: application/rdf+xml" http://purl.org/dc/terms/description`


kr,

Bert

**Comment by delahousse** [comment]
Can you send me the file you are talking about ?
Best regards
Jean

Jean Delahousse

Independent consultant
Knowledge Graph, Ontology, Linked Open Data, Open Data
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse


Le mar. 23 avr. 2019 à 10:20, bertvannuffelen <notifications@github.com> a
écrit :

**Comment by bertvannuffelen** [comment]
Hi Jean,

I was talking about these files: https://github.com/SEMICeu/DCAT-AP/tree/master/releases/1.2
kr,

Bert

**Comment by delahousse** [comment]
Dear Bert,

I'd like to be more useful, but I don't think I can help. The work done for
dcat-ap seems more recent than the work I did for dcat-ap-op. It is very
possible there is some points to be changed in dcat-ap-op to be completely
conformant to dcat-ap 1.2.
Today I do not have any mission from OP to work on this subject, but I can
take note the incompatibility you highlighted. I copy Simon Steuer who is
in charge of this project for Open Data Portal at OP.

Best regards
Jean


Jean Delahousse

Independent consultant
Knowledge Graph, Ontology, Linked Open Data, Open Data
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse


Le mar. 23 avr. 2019 à 11:43, bertvannuffelen <notifications@github.com> a
écrit :

**Comment by addragan** [comment]
Proposed resolution: Create an RDF representation where we define owl properties so it is compatible with Protégé.

**Comment by NatasaSofou** [comment]
Proposed resolution: As explained above, the issue occurs because DCAT-AP is an RDF vocabulary and not an OWL ontology. We will consider the creation of an OWL representation of the specification in the future.
