### ISSUE TITLE
dcat:CatalogRecord 

### ISSUE THREAD

**Issue by HelloLudger** [SEMICeu/DCAT-AP#53]
According to the 1.2 PDF:
> It MUST take one of the values :created, :updated or :deleted depending on whether this latest revision is a result of a creation, update or deletion.

Where are :created, etc. defined? 

The W3C (https://www.w3.org/TR/vocab-dcat/#class-catalog-record) doesn't say anything about this property.

Adding some information:
Section "4.2.1. Mandatory properties for Catalogue Record" lists the property "change type" with the URI "adms:status". The quote at the beginning is about this property.

It connects to 
https://github.com/SEMICeu/dcat-ap_shacl/issues/5
and #45

**Comment by akuckartz** [comment]
More info here:
https://joinup.ec.europa.eu/discussion/pr7-clarify-different-semantics-admsstatus-catalogrecord-and-distribution

**Comment by addragan** [comment]
Proposed resolution: Correct the documentation specification with the real statuses allowed by adms:status meaning Completed, Deprecated, UnderDevelopment and Withdrawn.

**Comment by NatasaSofou** [comment]
This issue is  related to #86 , #45

**Comment by bertvannuffelen** [comment]
resolution: removal of the reference to a non-existing controlled vocabulary + adding a topic for future work..
