### ISSUE TITLE
check existence of URIs

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#57]
Sometimes it is best to include a persistence quality check on the used predicates.

E.g. http://labs.mondeca.com/vocab/voaf is dead. It is also a domain that is likely to be changed, or possibly abandoned in the future. Even the company does and has done great work for the semantic web, it is not wise to depend a standard on a companies domain. 

btw. it happened in the recent past also for more reliable source such as dcterms, void that they were not anymore accessible.

**Comment by addragan** [comment]
Proposed resolution: Perform a persistence quality to clean up the existence of URIs used as predicates.

**Comment by init-dcat-ap-de** [comment]
Does DCAT-AP use the VOAF and the VANN namespace at all?
After a quick scan I couldn't find them in the document or the UML diagram.
Or is there another reason to list them?

**Comment by andrea-perego** [comment]
1. The persistent namespace for VOAF is http://purl.org/vocommons/voaf
2. And for VANN is http://purl.org/vocab/vann/
3. As far as I remember, VOAF and VANN are used in the RDF representation of DCAT-AP for describing the vocabulary itself.

**Comment by bertvannuffelen** [comment]
resolution: resolved.
