### ISSUE TITLE
json-ld > usage of @type

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#59]
The usage of the "@type" field makes the creation of json-ld structures more complicated

Example in [playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%7B%22accessRights%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FaccessRights%22%2C%22%40type%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FRightsStatement%22%7D%2C%22accessRights2%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FaccessRights2%22%2C%22%40type%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FRightsStatement%22%7D%2C%22accessRights3%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FaccessRights3%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22accessRights4%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2FaccessRights4%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fsomeorg.org%2Fdataset1%22%2C%22accessRights%22%3A%22http%3A%2F%2Fdomain%2Fmyrights%22%2C%22accessRights2%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fdomain%2Fmyrights%22%7D%2C%22accessRights3%22%3A%22http%3A%2F%2Fdomain%2Fmyrights%22%2C%22accessRights4%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fdomain%2Fmyrights%22%7D%7D)

```
{"@context" : { "accessRights":{
			"@id":"http://purl.org/dc/terms/accessRights",
			"@type":"http://purl.org/dc/terms/RightsStatement"
}, 
               "accessRights2":{
			"@id":"http://purl.org/dc/terms/accessRights2",
			"@type":"http://purl.org/dc/terms/RightsStatement"
}, 
               "accessRights3": { "@id" : "http://purl.org/dc/terms/accessRights3", "@type": "@id"},
              "accessRights4": { "@id" : "http://purl.org/dc/terms/accessRights4", "@type": "@id"}
              },
 
 "@id": "http://someorg.org/dataset1",
 "accessRights": "http://domain/myrights",
 "accessRights2": {"@id": "http://domain/myrights"},
 "accessRights3": "http://domain/myrights",
 "accessRights4" : {"@id" : "http://domain/myrights"
                   }
                   }
 ```
shows that the current way of specifying results in an incorrect mapping
```
<http://someorg.org/dataset1> <http://purl.org/dc/terms/accessRights2> <http://domain/myrights> .
<http://someorg.org/dataset1> <http://purl.org/dc/terms/accessRights3> <http://domain/myrights> .
<http://someorg.org/dataset1> <http://purl.org/dc/terms/accessRights4> <http://domain/myrights> .
<http://someorg.org/dataset1> <http://purl.org/dc/terms/accessRights> "http://domain/myrights"^^<http://purl.org/dc/terms/RightsStatement> .
```

namely using the object range as a datatype.

**Comment by addragan** [comment]
Proposed resolution: Proposal to deprecate the JSON-LD distribution and no longer accept new change requests for it.

**Comment by akuckartz** [comment]
> deprecate the JSON-LD distribution

@addragan can you elaborate please?

**Comment by jakubklimek** [comment]
@addragan I do not understand. From your example, I get that the JSON-LD @context was written wrong. Why not just fix it instead of deprecating it, when JSON-LD is gaining traction on the Web?

**Comment by addragan** [comment]
@akuckartz @jakubklimek In the DCAT-AP major release webinar on 12 June 2019, it was proposed to focus on the development of the DCAT-AP SHACL representation in favour of other distributions like RDF and JSON-LD. For this reason, it was proposed to stop taking requests for the JSON-LD representation. This will happen only if we reach consensus so please be invited to contribute by commenting on the open issues in the repository.

**Comment by bertvannuffelen** [comment]
@addragan I have not participated to the webinar, but the argument you are giving here seems really counterintuitive. SHACL cannot exists without RDF, it is a language expressing constraints on RDF graphs. So the RDF and hence JSON-LD representations are part of the SHACL work.
How otherwise are you going to test the SHACL shape? using a CSV document by manual inspection?

In the end we are exchanging DCAT-AP data representations. The SHACL is there to support the quality control of those representations.

So I strongly disagree with the proposed solution because of the argumentation provided. Deprecation is not the answer to the issue of focussing editorial efforts. 
And as @jakubklimek stated, json-ld is the main entrance point for people to the semantic world so I would embrace quality json-ld contexts instead of deprecating them ;-)

**Comment by giorgialodi** [comment]
I strongly agree with @bertvannuffelen  DCAT, from which DCAT-AP is born,  is a Web standard **based on RDF**; JSON-LD is one of the serializations of RDF data representation model for the JSON (web based development) environment. SHACL is "_SHACL Shapes Constraint Language, a language for validating RDF graphs against a set of conditions_" therefore it cannot be put in contrast with RDF serializations.  I would strongly suggest to keep all the RDF serializations of DCAT-AP with its validation form via SHACL

**Comment by fsantiagoEC** [comment]
In my view, JSON-LD does not support any kind of contraints or limitations, so, but for specific properties that may appear in DCAT-AP and not in DCAT, there would be not JSON-LD representation for DCAT-AP but for DCAT, right?

**Comment by bertvannuffelen** [comment]
@fsantiagoEC  I do not completely understand your remark, but I will try to provide an approach that we in Flanders are following which might tackle your concerns.

For exchanging data between systems we like to use only dataformats with embedded semantics. This holds for RDF standard serializations, provided that all predicates and classes are well-defined.
JSON-LD is a recent form of embedding semantics in a non-semantic dataformat JSON. It does it by extending the JSON with hooks that allow a unique mapping to a RDF graph.
Unique for JSON-LD is that these hooks are standarized by W3C. So one can rely on them.

For XML, in the context of WSDL, a similar idea has been explored. But that ended on only standarizing de hook  that corresponds to the "@context" attribuut. Other hooks that standarize the mapping were not taken into consideration. 

This json-ld approach allows to contain the json payload more data than DCAT-AP specifies. It even allows for other terms for the attributes (very handy in a multi-lingual context). But given a proper json-ld context we are guaranteed to get a RDF graph.

This RDF graph we can validate using the SHACL templates to see it complies.  If it does, the original json-ld file does. 

Providing a json-ld context with the DCAT-AP  specification is assisting the tool developers. Namely they know if they use these terms, their json payload ends up in the correct RDF graph. And hence has a potential to be compliant with the DCAT-AP specification. Otherwise they have to do all the work again to create a correct RDF graph.  

And probably because developers are lazy people (which is a good attitude) the likely hood exists that the exchanged payloads of different APIs and systems become syntactically alike. For the semantics this is not necessary, but code reuse wise it is. 

Our argument in this track is that expressing constraints using SHACL  is not an argument to stop supporting the developers creating the RDF representations. Both are needed.

**Comment by addragan** [comment]
Proposed resolution: Simplify the json-ld structure by modifying the @type field.
