### ISSUE TITLE
Make ISA Open Metadata license more referable

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#63]
DCAT-AP is published using the ISA Metadata license.
Unfortunately this license has now stable URI identifier to reference it, nor the Open Source Institute achknowledged this licence.

We suggest that ISA gives a stable URI to reference this license and to make it an official open license acknowledged by OSI, ODI, or other institutes.

See also: https://github.com/GovDataOfficial/DCAT-AP.de/issues/5

**Comment by akuckartz** [comment]
The ISA Metadata license is about *data* while the Open Source Institute licenses are about *source code*.

**Comment by sandervd** [comment]
Same as in
https://github.com/catalogue-of-services-isa/CPSV-AP/issues/38#issuecomment-514966704
To consider moving to Creative Commons...

**Comment by bertvannuffelen** [comment]
resolution: replaced by cc-by 4.0
