### ISSUE TITLE
dcat:Dataset: make dct:temporal recommended?

### ISSUE THREAD

**Issue by ldibanyez** [SEMICeu/DCAT-AP#64]
There is evidence that people searches for datasets with temporal filters in mind (e.g. [1]).
Making dct:temporal recommended would help search engines and metaportals.

One question though is what value should be used for datasets that do not have a temporal period, in order to differentiate "This dataset does not have a temporal period" of "This dataset is missing a temporal period value". 

This is related to issue #9 

[1] https://eprints.soton.ac.uk/426734/

**Comment by bertvannuffelen** [comment]
resolution: dct:temporal is recommended for dcat:Dataset
