### ISSUE TITLE
New implementation of DCAT-AP for GeoNetwork

### ISSUE THREAD

**Issue by stijngoedertier** [SEMICeu/DCAT-AP#65]
There is an implementation of DCAT-AP 1 as a schema plugin for GeoNetwork.

https://github.com/metadata101/dcat-ap1.1

The work was funded by and carried out in close collaboration with Informatie Vlaanderen (AIV) from Belgium.

**Comment by andrea-perego** [comment]
Thanks for sharing this, @stijngoedertier .

Could you provide more details of the actual DCAT-AP support provided by this plugin? It does also support GeoDCAT-AP?

**Comment by stijngoedertier** [comment]
Dear Andrea, apologies for my late reply, but thanks for your interest in the [GeoNetwork plugin](https://github.com/metadata101/dcat-ap1.1). To reply to your question, no, it unfortunately does not provide support for the GeoDCAT-AP Extended profile,  only for DCAT-AP v1.2.  
There is support for editing of (multilingual) metadata, validation, mandatory controlled vocabularies, faceted search, and harvesting of remote DCAT-AP endpoints. 

As schema plugins in GeoNetwork require a specific XML Schema,  we created _an_ [XML Schema for DCAT-AP v1.1](https://github.com/metadata101/dcat-ap1.1/tree/master/src/main/plugin/dcat-ap/schema) that could also pass as an RDF/XML metadata representation. Adding support for GeoDCAT or for [DCAT v2.0](https://www.w3.org/TR/vocab-dcat-2/) would require updating that schema (form configurations, etc.)... and thus creating a new schema plugin. To my knowledge, there are no concrete plans yet to upgrade.

**Comment by sgrellet** [comment]
back on that thread.
@andrea-perego : is there a plan to provide a xsd based on DCAT 2.0 ? After some seaching I found this attempt (https://github.com/pwin/dcat-v2-xml-schema/tree/master/schema) which is now outdated. Several of us are willing to have Geonetwork evolve to take it into account. The updated schema is defintely the 1st step. Merci.Sylvain

**Comment by andrea-perego** [comment]
Not to my knowledge, @sgrellet . 

However, if the final objective is to use it in GeoNetwork, an option could be to build upon the plugin reported by @stijngoedertier , and it may also be worth checking if any native support to DCAT/DCAT-AP is planned in GeoNetwork ( /cc @pvgenuchten ).

**Comment by pvgenuchten** [comment]
hi, would love to chat about the idea of native support. From a geonetwork perspective the plugin mentioned by Stijn introduces DCAT as a native format. However it is not as native as the RDF community may expect. We store the record as a blob in a specific form of RDF/XML. The tools to convert any DCAT RDF to that specific form are currently out of scope of GeoNetwork (correct @stijngoedertier?). It means that we can't currently harvest DCAT records from for example a SPARQL endpoint.

**Comment by bertvannuffelen** [comment]
There is now a DCAT2 plugin: https://github.com/metadata101/dcat2
