### ISSUE TITLE
Add dcat:Resource as a superclass of dcat:Dataset and dcat:Catalog

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#66]
Add new class dcat:Resource, superclass of dcat:Dataset, dcat: Catalog, dcat:DataService  with properties  dct:accessRights, dct:conformsTo, dcat:contactPoint, dct:description, dct:title, dct:issued, dct:modofied, dct:language, dct:publisher, dct:identifier, dct:type, dct:relation, dcat:theme, dcat:keyword, dcat:landingPage, dct:licence, dct:rights

**Comment by init-dcat-ap-de** [comment]
Just to be sure: dct:license (as one big difference to CKAN) will no longer be present only at distribution and catalogue level?
Adding dct:license to dcat:resource and deriving dcat:dataset from superclass dcat:resource will result in the new possibility to declare a license at distribution, catalogue AND at dcat:dataset level? 

If so, please indicate a rule where to look for the truth if both levels are used inconsistently. 
Is dct:license at dataset level the license for the metadata of the dataset in contrast to dct:license at distribution level which as specifiied "the license of the distribution" or are both dct:license meant to be the license of the data that the distribution accessURL is pointing to?
Thank you in advance for a clarification.

**Comment by jakubklimek** [comment]
@init-dcat-ap-de This is stated in https://w3c.github.io/dxwg/dcat/#Property:distribution_license - i.e. licenses still should be on distribution level. On dataset level, they may be provided in addition, not instead of the distribution level, and there should not be conflicts.

**Comment by NatasaSofou** [comment]
Propose resolution: dcat:Resource  has been introduced as an "extension" point for resource types, so there is currently no need to be explicitly  added to  DCAT-AP.

**Comment by paulakeen** [comment]
And still we need the properties "conformsTo" and "identifier", what do we do then?
