### ISSUE TITLE
Add new properties to dcat:Resource

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#67]
In dcat:Resource, add new properties  

- odrl:hasPolicy: A policy expressing the rights associated with the resource if using the ODRL vocabulary
- dct:isReferencedBy: A related resource, such as a publication, that references, cites, or otherwise points to the cataloged resource.
- dcat:qualifiedRelation : Link to a description of a relationship with another resource
- prov:qualifiedAttribution : Link to an Agent having some form of responsibility for the resource
- dct:creator: The entity responsible for producing the resource.

**Comment by NatasaSofou** [comment]
Proposed resolution: Since dcat:Resource will not be added explicitely in DCAT-AP, properties will be added to dcat:Dataset.

**Comment by bertvannuffelen** [comment]
proposal: accepted
