### ISSUE TITLE
dcat:Dataset - how to encourage the use of dct:description?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#7]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:description (mandatory property)

- Usage: 96.46% of the datasets queried
- Should we somehow encourage addition of description to the 26,328 datasets that don’t use this mandatory property?

**Comment by peterk** [comment]
It is reasonable to argue that without even a simple description discovery and re-use becomes a lot more difficult. Would it be possible to gather contact details of these datasets either at org level or for the individual datasets and mass-email perpetrators?

**Comment by giorgialodi** [comment]
In the Italian profile the property is mandatory. At the time being, for all those datasets compliant with the profile a description is there :) We imposed that  just because without this minimum information the discovery and re-use is very difficult, I agree. Why don't we consider it as mandatory?

**Comment by makxdekkers** [comment]
@giorgialodi The property is mandatory at the moment and I haven't heard any suggestion that this obligation should be relaxed. The question is whether we need to try to get descriptions of the 3% of datasets that don't have them.

**Comment by makxdekkers** [comment]
@peterk In the work that was done to look at DCAT-AP usage, we focused on simple statistics. We did not look at exactly which datasets or which data providers violated the rule that description is mandatory. It could be a role for aggregators to provide feedback to the data providers when mandatory properties are missing (e.g. using the [DCAT-AP validator](https://github.com/SEMICeu/dcat-ap_validator) or [SHACL ](https://github.com/SEMICeu/dcat-ap_shacl). Also, users could provide feedback if they encounter such datasets.

**Comment by giorgialodi** [comment]
You are right @makxdekkers, sorry my mistake! I would be very severe: all datasets that do not comply with the minimum requirements defined by the profile are out in any data catalogue. It is a matter of quality of metadata that facilitates the reuse. In this sense, EDP should lead by example :)

**Comment by makxdekkers** [comment]
Proposed resolution | No change to the specification.

**Comment by addragan** [comment]
The issue will be close and no changes will be done to the specification.
