### ISSUE TITLE
Make dcat:Catalog subclass of dcat:Dataset

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#70]

**Comment by HelloLudger** [comment]
This should result in Catalog being able to use all properties from Dataset, shouldn't it?

Including but not limited to 'keyword' being recommended for Catalogs?

Shouldn't these information be visible not only in the rdf but also in the AP document?

**Comment by bertvannuffelen** [comment]
The mandatory and recommended qualification will be explicitly stated in the specification. If the property is not mentioned but would be derived applicable for a class according to DCAT 2.0 specification then the semantics is identical to DCAT 2.0. En being optional.

**Comment by fellahst** [comment]
The subclassing of dcat:Catalog from dcat:Dataset is problematic and a mistake in my opinion. It reduces its reusability, While Catalog class can reuse many properties of Dataset, does not mean it is should be a subclass of Dataset.  In Geoplatform, a Catalog can refer to different types of assets (closely matching to dcat:Resource) including maps, layers, services, reports etc. We define the term Portfoli as a subclass of dcat:Catalog. Catalog could also be specialized as a Collection, Series or Aggregation of assets, e.g. map series, datasets series, image collection etc..

**Comment by bertvannuffelen** [comment]
@fellahst thank you for your feedback, but your comment about the subclassing is one which should not be addressed here but at the W3C DCAT 2.0, see https://github.com/w3c/dxwg/issues.
The topics discussed here for the release DCAT-AP 2.0 are about the alignment of DCAT-AP with DCAT-AP 2.0. The arguments pro and contra for that decision can be found there.
