### ISSUE TITLE
Relax range of dcat:themeTaxonomy (in dcat:Catalog)

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#71]
In dcat:Catalog, relax the range of dcat:themeTaxonomy and make it rdfs: Resource

**Comment by akuckartz** [comment]
Why? It currently is skos:ConceptScheme which seems to be appropriate.

**Comment by bertvannuffelen** [comment]
resolution: maintain skos:ConceptScheme
