### ISSUE TITLE
Add new properties to dcat: Catalog

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#72]
Add  new properties dcat:catalog, dcat:service to dcat:Catalog

**Comment by NatasaSofou** [comment]
Proposed resolution: Add properties:

- dcat:service
- dcat:catalog
- dcat:creator

**Comment by bertvannuffelen** [comment]
resolution: accepted proposal for properties dcat:service, dcat:catalog and dct:creator
