### ISSUE TITLE
In dcat:Dataset add properties dcat:temporalResolution, dcat:spatialResolutionInMeters  

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#76]
Class dcat:Dataset, add properties :   

- dcat:temporalResolution: specifies temporal resolution resolvable in a dataset
- dcat:spatialResolutionInMeters: specifies spatial resolution resolvable in a dataset in meters

**Comment by NatasaSofou** [comment]
Proposed resolution:  Add  optional properties:

- dcat:temporalResolution
- dcat:spatialResolutionInMeters

**Comment by init-dcat-ap-de** [comment]
The range of dcat:temporalResolution is xsd:duration, for dcat-ap.de we use dcat:granularity for the temporal granularity of the data, but there we have rdfs:Ressource as Range.
We use http://publications.europa.eu/resource/authority/frequency for this.

While the properties sound pretty similar, they are not. With our solution, we can say how often e.g. a sensor is creating data. (http://publications.europa.eu/resource/authority/frequency/MONTHLY), this is not possible with xsd:duration.

Has anyone else have a need for this kind of temporal granularity?

**Comment by init-dcat-ap-de** [comment]
Yes, we could and this seems to be the solution according to the W3C. See: https://github.com/w3c/dxwg/pull/776#issuecomment-547836546

But this results in different meanings of dcar:temporalResolution depending on the context of the use. 
And I see no way to say "The dataset includes avarenge temperatur of the last minute (resolution) measured every hour (frequency)."
Or "The sensor reports every hour if it was raining within the last five minutes".

**Comment by bertvannuffelen** [comment]
resolution: properties added, usage guidelines tagged as future-work

**Comment by matthiaspalmer** [comment]
I think both dcat:temporalResolution and dcat:spatialResolutionInMeters should have a maximum cardinality of 1, currently it says "0..n" in the specification.
