### ISSUE TITLE
In dcat:Distribution, add  new properties odrl:hasPolicy,  dcat:accessService 

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#77]
In dcat:Distribution, add  new properties:
- odrl:hasPolicy:   to specify an ODRL conformant policy expressing the rights associated with the distribution.
- dcat:accessService: to specify a data service that gives access to the distribution of the dataset

**Comment by bertvannuffelen** [comment]
resolution: accepted
