### ISSUE TITLE
In dcat:Distribution, add new properties  dcat:spatialResolutionInMeters, dcat:temporalResolution

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#78]
In dcat:Distribution, add new properties:

- dcat:spatialResolutionInMeters: to specify the minimum spatial separation resolvable in a dataset distribution, measured in meters.
- dcat:temporalResolution: to specify the minimum time period resolvable in the dataset distribution.

**Comment by bertvannuffelen** [comment]
resolution: accept the addition of new properties

**Comment by matthiaspalmer** [comment]
Just like on the dataset level:
I think both dcat:temporalResolution and dcat:spatialResolutionInMeters should have a maximum cardinality of 1, currently it says "0..n" in the specification.
