### ISSUE TITLE
In dcat:Distribution, add new properties dcat:packageFormat , dcat:compressFormat 

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#79]
In dcat:Distribution, add new properties:
- dcat:packageFormat: to specify the  package format of the distribution in which one or more data files are grouped together, 
-  dcat:compressFormat : to specify the  compression format of the distribution

**Comment by sandervd** [comment]
The cardinality of this property should be discussed taking #49 into consideration.

**Comment by bertvannuffelen** [comment]
resolution: align the cardinality for these properties
