### ISSUE TITLE
dcat:Dataset - use of dct:publisher and dcat:contactPoint

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#8]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:publisher and dcat:contactPoint
•	Usage: 43.85% and 45.44% respectively; 5.2% use both properties
•	How could we promote the usage of these recommended properties, in addition to the guideline “How are publisher and contact point modelled”?.

**Comment by brechtwyns** [comment]
Input from the working group: "since EDP does not show from which catalog a dataset comes from (only the national level is shown) dct:publisher is vital"

**Comment by makxdekkers** [comment]
If the information about the publisher of the dataset is "vital" as per the input from the WG at the [Webinar on 8 December 2017](https://joinup.ec.europa.eu/node/700137), should we consider to make the property mandatory? Or would this be too strict, given that currently this information is not available for more than half of the datasets?

**Comment by makxdekkers** [comment]
Please note there is a discussion in the W3C DXWG about the [domain](https://github.com/w3c/dxwg/issues/95) and [range](https://github.com/w3c/dxwg/issues/109) of dcat:contactPoint.
The domain restriction is likely to be dropped and the range may be widened to also allow other ways of providing contact information.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by addragan** [comment]
Issue rejected due to disagreement comments. The issue will be closed with no changes in the specification.
