### ISSUE TITLE
Add new class dcat:Role

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#82]
Add new class **dcat:Role** (subclass of skos:Concept )  as the function of a resource or agent with respect to another resource, in the context of resource attribution or resource relationships. It complements prov:Role which provides the function of an entity or agent with respect to an activity.

**Comment by NatasaSofou** [comment]
Proposed resolution: add optional class dcat:Role

**Comment by bertvannuffelen** [comment]
resolution: accepted
