### ISSUE TITLE
Add new properties to dct:Location 

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#85]
In dct:Location, add properties:
- lcon:geometry: Associates any resource with the corresponding geometry
- dcat:bbox: Specifies the geographic bounding box of a resource.
- dcat:centroid: Specifies the geographic center (centroid) of a resource.

**Comment by NatasaSofou** [comment]
Proposed resolution: in **dct:Location** class, add properties:

- lcon:geometry (optional) 
- dcat:bbox (recommended)
- dcat:centroid (recommended)

**Comment by andrea-perego** [comment]
Not sure about which should be optional and which recommended.

The point is that these three properties have different purposes. So, whether they are recommended or not depends on their use, as also stated in [the usage note of `dct:Location` of the DCAT2 specification](https://w3c.github.io/dxwg/dcat/#Class:Location) - quoting:

> - For an extensive geometry (i.e., a set of coordinates denoting the vertices of the relevant geographic area), the property locn:geometry [LOCN] SHOULD be used.
> - For a geographic bounding box delimiting a spatial area the property dcat:bbox SHOULD be used.
> - For the geographic center of a spatial area, or another characteristic point, the property dcat:centroid SHOULD be used.

Moreover, as `locn:geometry` is already being used in (Geo)DCAT-AP - usually for bounding boxes - backward compatibility should be taken into account.

Based on this, an option is to make `locn:geometry` recommended, and `dcat:bbox` and `dcat:centroid` optional, adding however a note saying that they are recommended when the geometry is a bbox or a centroid, respectively.

**Comment by bertvannuffelen** [comment]
@andrea-perego currently the proposed specification implements the required level of those properties inversely: recommended are dcat:bbox and dcat:centroid and locn:geometry is optional.

This with the argumentation in the usage note:
```Please note that the order of usage is as follows : use the most specific geospatial relationship by preference. E.g. if the spatial description is a bbox, use dcat :bbox, otherwise use locn:geometry
```

Note that existing approaches would not be incompatible, they merely are based on this adviced to investigate if the provided spatial descriptions fall in one of the two specific cases.
