### ISSUE TITLE
SHACL  dcterms:publisher too strict ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/DCAT-AP#87]
dcat-ap_1.2.1_shacl_mdr-vocabularies.shape.ttl seems to impose :CorporateBodyRestriction shape on all dct:publisher

More specifically, they constraint limits skos:inScheme to <http://publications.europa.eu/resource/authority/corporate-body>, 
which will not work for organisations not part of this taxonomy.

DCAT 1.2.1 spec mentions (p 20)
"The Corporate bodies NAL must be used for European institutions and a small set of international organisations. In case of other types of organisations, national, regional or local vocabularies should be used."

So the suggestion is to drop the skos:inScheme constraint

**Comment by barthanssens** [comment]
Also seems to be present in DCAT 2.0 SHACL

**Comment by bertvannuffelen** [comment]
Will be addressed in DCAT-AP 2.0 shacl.

If interest by the community the DCAT-AP 1.2.x version can be updated too.

**Comment by barthanssens** [comment]
I think it would be interesting to update the DCAT-AP 1.2.x SHACLs, since they are being used by the European Dataportal  Metadata quality tool / dashboard (https://www.europeandataportal.eu/mqa)

**Comment by benjamin-dittwald** [comment]
I'm in lead of the technical core components of the European Data Portal and I like to emphasize, that we are indeed interested in updated SHACL rules for 1.2.x and 2.0.

**Comment by bertvannuffelen** [comment]
resolution: added severity level to the controlled vocabularies. For those that can be overwritten with local versions severity warning is used.

**Comment by bertvannuffelen** [comment]
The shacl files and testbed have been updated. The shacl file specification style for release 2.0.0 has been applied on release 1.2.1 retroactively. A new release of 1.2.1 has been done.
In the testbed https://www.itb.ec.europa.eu/shacl/dcat-ap/upload one find now the validation w.r.t. release 1.2.1 and 2.0.0.
