### ISSUE TITLE
dct:language NAL also for Distribution/CatalogueRecord

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/DCAT-AP#88]
Related to #55 

The DCAT-AP 1.2.1 spec (5.2. Controlled vocabularies to be used) mentions that the EU Vocabularies Languages Named Authority List is to be used for dct:language on Catalogue and Dataset.

But dct:language is also a property on Distribution and CatalogueRecord.

Recommended solution is to also require the use of the EU Languages NAL for Distribution and CatalogueRecord.

**Comment by bertvannuffelen** [comment]
Will be addressed for release DCAT-AP 2.0. 

If the community expects an additional retrofit on DCAT-AP 1.2.x, please let us know.

**Comment by bertvannuffelen** [comment]
resolution: proposal accepted
