### ISSUE TITLE
dcat:Dataset - dct:spatial recommended?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#9]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:spatial
•	Usage: 76.79%
•	Should this property be made recommended?

**Comment by makxdekkers** [comment]
If there is no strong support for making this property recommended, I would propose to leave things as they are.

**Comment by makxdekkers** [comment]
Proposed resolution | Make dct:spatial recommended for Dataset.

**Comment by ldibanyez** [comment]
I agree with this property being recommended. Not that much because sources are using it, but because there is evidence that is important for how people search datasets (e.g. [1])

[1] https://eprints.soton.ac.uk/426734/

**Comment by bertvannuffelen** [comment]
resolution: recommand dct:spatial
