### ISSUE TITLE
dcat:dataset property recommended instead of mandatory

### ISSUE THREAD

**Issue by espinr** [SEMICeu/DCAT-AP#91]
Now that `dcat:Catalog`s may contain `DataServices` and/or `Datasets`, the property `dcat:dataset` of `Catalog` should be recommended (0..n) instead of mandatory (1..n).

**Comment by bertvannuffelen** [comment]
This is raises a fundamental question to the nature of DCAT-AP. It is conceived as a specification for Open Data catalogs serving Open Data datasets (starting from the dataset perspective).  With DCAT 2.0 indeed the notion of an service gets a proper place. But what is an Open Data service? What is a catalog with only data services? Is that within the scope of DCAT-AP?

Given that data services are novel entities, but addressing to an high demand by the community, the proposal is for release DCAT-AP 2.0 not to adopt the proposal now. But take this as a starting point for a future release.

**Comment by bertvannuffelen** [comment]
During WG 15 sept 2021 and WG 21 Oct 2021, the wg was presented an approach to address the questions related to this issue. The result is an updated UML diagram and an usage guideline for Datasets, Distributions and Data Services.
