### ISSUE TITLE
Missing dct:rights on Data Service

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#96]
It is important to specify the terms of use of a data service, and especially for open data and open APIs.

Therefore, I propose that `dct:rights` is recommended both for distribution and data service. Currently, on Data Service, it is missing completely in DCAT-AP 2.0.0.

**Comment by bertvannuffelen** [comment]
resolution: since this requires more discussion on how license and rights are combined and interrelate, and what are the guidelines to be included in DCAT-AP, this postponed for a future release.

**Comment by bertvannuffelen** [comment]
**updated proposed resolution**
to maintain the specification as is.  

**motivation**

- dct:rights is not forbidden to be used by a local profile, thus local profile providers can supply the data.
- dct:license is qualified as recommended property (not mandatory), therefore not providing a licence is conform DCAT-AP
- W3C DCAT (https://w3c.github.io/dxwg/dcat/#license-rights) expresses generic good guidelines. These should be followed.
